SHELL := /usr/bin/env bash

include cfg/codex-frontend.mk
# include cfg/django.mk
# include cfg/frontend.mk
# include cfg/python.mk
# include cfg/ci.mk
# include cfg/docker.mk
# include cfg/docs.mk
include cfg/common.mk
include cfg/help.mk

.PHONY: all
