services:
  ci:
    build:
      context: .
      target: codex-ci
    container_name: ${CI_CONTAINER}
    entrypoint:
      - sleep
      - infinity
    environment:
      - PYTHONUNBUFFERED=1
    image: ${CI_IMAGE}
    volumes:
      - ./test-results:/app/test-results
      - ./dist:/app/dist
  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/config/nginx/site-confs/default.conf:ro
