FROM ajslater/codex-builder:groovy_1.4.0-49c2f4b


ARG DEBIAN_FRONTEND=noninteractive

####################
# APP DEPENDENCIES #
####################

WORKDIR /app
COPY pyproject.toml poetry.lock /app/
RUN poetry install --no-root --remove-untracked
COPY frontend/package.json frontend/package-lock.json /app/frontend/
WORKDIR /app/frontend
RUN npm install

########
# TEST #
########

WORKDIR /app
RUN echo "**** copying source for dev build ****"
COPY . .
RUN echo "*** run lint ***"
RUN ./lint.sh

RUN echo "*** run tests ***"
RUN ./test.sh

#########
# BUILD #
#########

WORKDIR /app/frontend
RUN echo "*** build frontend ***" && \
  rm -rf ../codex/static_build && \
  npm run build

WORKDIR /app
RUN echo "*** collect static resources in one place ***" && \
  ./collectstatic.sh

# XXX poetry auto-excludes anything in gitignore. Dirty hack around that.
RUN echo "*** build and package application ***" && \
  sed -i "s/.*static_root.*//"  .gitignore && \
  poetry build

VOLUME /dist
VOLUME /test-results
CMD ["./build-copy-artifacts.sh"]
