_PermissionClass  # unused import (codex/views/admin/auth.py:13)
exitstatus  # unused variable (tests/conftest.py:7)
format_suffix  # unused variable (codex/views/opds/binary.py:27)
Literal  # unused import (codex/librarian/onlinetag/session_manager.py — string-form cast)
ManyToManyRel  # unused import (codex/librarian/scribe/importer/link/delete.py:18)
mock_bytes  # @patch positional mock arg (tests/test_admin_custom_cover.py)
Mode  # unused import (codex/librarian/scribe/tag_writer.py — string-form cast)
sender  # unused variable (codex/librarian/scribe/importer/pragmas.py:77)
