_PermissionClass  # unused import (codex/views/admin/auth.py:13)
format_suffix  # unused variable (codex/views/opds/binary.py:27)
sender  # unused variable (codex/librarian/scribe/importer/pragmas.py:77)
ManyToManyRel  # unused import (codex/librarian/scribe/importer/link/delete.py:18)
Literal  # unused import (codex/librarian/onlinetag/session_manager.py — string-form cast)
Mode  # unused import (codex/librarian/scribe/tag_writer.py — string-form cast)
