# Generated by Django 3.1b1 on 2020-07-07 23:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="cover_path",
            field=models.CharField(max_length=32),
        ),
    ]
