# Generated by Django 3.0.5 on 2020-04-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='folder',
            new_name='parent_folder',
        ),
    ]
