# Generated by Django 3.0.4 on 2020-04-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imprint',
            old_name='default',
            new_name='is_default',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='default',
            new_name='is_default',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='default',
            new_name='is_default',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='default',
            new_name='is_default',
        ),
        migrations.AlterUniqueTogether(
            name='imprint',
            unique_together={('name', 'publisher', 'is_default')},
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('name', 'is_default')},
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('name', 'imprint', 'is_default')},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('name', 'series', 'is_default')},
        ),
    ]
