"""Generated by Django 3.1 on 2020-08-26 06:22."""

from django.db import migrations


class Migration(migrations.Migration):
    """Change libraries verbose name."""

    dependencies = [
        ("codex", "0001_init"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={"verbose_name_plural": "libraries"},
        ),
    ]
