# Generated by Django 3.0.4 on 2020-03-17 03:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="cover_image",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="path",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="rootpath",
            name="last_scan",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="rootpath",
            name="path",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
