# Generated by Django 3.1rc1 on 2020-07-29 00:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0002_auto_20200707_2353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminflag",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="comic",
            name="country",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="critical_rating",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="date",
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="decade",
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="issue",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0.0, max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="language",
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="maturity_rating",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="page_count",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="comic",
            name="size",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="sort_name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="comic",
            name="title",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="comic",
            name="user_rating",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="creditperson",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="creditrole",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="imprint",
            name="sort_name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="library",
            name="enable_scan_cron",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="library",
            name="enable_watch",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="sort_name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="series",
            name="sort_name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="seriesgroup",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="storyarc",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="userbookmark",
            name="bookmark",
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="userbookmark",
            name="finished",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="volume",
            name="sort_name",
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
