# Generated by Django 3.0.4 on 2020-03-17 04:49

from django.db import migrations
from django.db import models

import codex.validators


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0002_auto_20200317_0326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpath",
            name="path",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[codex.validators.validate_path_exists],
            ),
        ),
    ]
