# Generated by Django 3.0.5 on 2020-04-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20200407_2059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('root_path', 'path', 'parent_folder', 'name')},
        ),
    ]
