# Generated by Django 3.1rc1 on 2020-07-29 00:08

from django.db import migrations
from django.db import models

import codex.models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0003_auto_20200729_0003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="path",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="folder",
            name="path",
            field=models.CharField(
                db_index=True,
                max_length=128,
                validators=[codex.models.validate_dir_exists],
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="path",
            field=models.CharField(
                db_index=True,
                max_length=128,
                unique=True,
                validators=[codex.models.validate_dir_exists],
            ),
        ),
    ]
