# Generated by Django 3.0.4 on 2020-03-17 04:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0003_auto_20200317_0449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpath",
            name="scan_frequency",
            field=models.DurationField(default=43200),
        ),
    ]
