# Generated by Django 3.1 on 2020-08-21 18:20

from django.db import migrations

from codex.models import AdminFlag


def init_admin_flags(apps, schema_editor):
    """Initalize the admin flag rows"""
    # AdminFlag = apps.get_model("codex", "AdminFlag")  # noqa N806
    obj_list = []
    for name in AdminFlag.FLAG_NAMES:
        obj_list.append(AdminFlag(name=name))
    AdminFlag.objects.bulk_create(obj_list)


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0001_squashed_0004_auto_20200729_0008"),
    ]

    operations = [migrations.RunPython(init_admin_flags)]
