# Generated by Django 3.2.9 on 2021-11-04 03:03

from django.db import migrations, models


MODEL_NAMES = {
    "Volume": "",
    "Series": "Default Series",
    "Imprint": "Main Imprint",
    "Publisher": "No Publisher",
}
NEW_DEFAULT_NAME = ""


def update_default_names(apps, schema_editor):
    """Prepare for removing the is_default field."""
    for model_name, default_name in MODEL_NAMES.items():
        model = apps.get_model("codex", model_name)
        model.objects.filter(name=NEW_DEFAULT_NAME, is_default=False).update(name="UNKNOWN")
        model.objects.filter(name=default_name, is_default=True).update(name=NEW_DEFAULT_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0005_auto_20200918_0146"),
    ]

    operations = [migrations.RunPython(update_default_names)]
