# Generated by Django 3.2.9 on 2021-11-04 03:03
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0006_group_default_name_empty_2021104_0341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imprint",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="codex.publisher"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="codex.publisher"
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="codex.publisher"
            ),
        ),
    ]
