# Generated by Django 3.2.9 on 2021-11-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0006_group_default_name_empty_20211104_0300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imprint",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="volume",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name="imprint",
            unique_together={("name", "publisher")},
        ),
        migrations.AlterUniqueTogether(
            name="publisher",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("name", "imprint")},
        ),
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together={("name", "series")},
        ),
        migrations.RemoveField(
            model_name="imprint",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="series",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="is_default",
        ),
    ]
