# Generated by Django 3.2.9 on 2021-11-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0007_auto_20211104_0341"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comic",
            old_name="folder",
            new_name="folders",
        ),
    ]
