"""Generated by Django 3.2.9 on 2021-11-04 03:03."""

from django.db import migrations


class Migration(migrations.Migration):
    """Make folders field name consistent with other m2m fields."""

    dependencies = [
        ("codex", "0007_publisher_delete_cascade_20211104_0400"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comic",
            old_name="folder",
            new_name="folders",
        ),
    ]
