# Generated by Django 3.0.5 on 2020-04-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_adminflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.Folder'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='root_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.RootPath'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Volume'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.CreditPerson'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.CreditRole'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='root_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.RootPath'),
        ),
        migrations.AlterField(
            model_name='series',
            name='imprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Imprint'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Series'),
        ),
    ]
