# Generated by Django 3.2.9 on 2021-11-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0008_rename_folder_comic_folders_20211104_0405"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=32)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
