"""Generated by Django 4.0 on 2021-12-19 17:47."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Override related_in becauese interferes with comic.folders."""

    dependencies = [
        ("codex", "0008_alter_comic_created_at_alter_comic_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="parent_folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comic_in",
                to="codex.folder",
            ),
        ),
    ]
