# Generated by Django 4.0.1 on 2022-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("codex", "0010_haystack"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="groups",
            field=models.ManyToManyField(blank=True, to="auth.Group"),
        ),
    ]
