"""Generated by Django 3.2.9 on 2021-11-19 22:50."""

from django.db import migrations
from django.db.models.functions import Now


UPDATE_FIELDS = ("stat", "updated_at")


def remove_duplicate_comics(apps, _schema_editor):
    """Remove duplicate comics in preparation for looser unique constraints."""
    model = apps.get_model("codex", "Comic")
    comics = model.objects.only("pk", "library__id", "path", "stat", "updated_at")
    unique = {}
    update_comics = {}
    delete_comics = set()
    now = Now()
    for comic in comics:
        dupe_id = (comic.library_id, comic.path)
        update_comic = unique.get(dupe_id)
        if update_comic:
            if update_comic.pk not in update_comics:
                update_comic.stat = None
                update_comic.updated_at = now
                update_comics[update_comic.pk] = update_comic
            delete_comics.add(comic.pk)
        else:
            unique[dupe_id] = comic

    if delete_comics:
        print()
        print(f"Deleting {len(delete_comics)} duplicate comics from database.")
        model.objects.filter(pk__in=delete_comics).delete()
    if update_comics:
        print(f"Marking {len(update_comics)} comics to be updated by the next poll.")
        model.objects.bulk_update(update_comics.values(), fields=UPDATE_FIELDS)


class Migration(migrations.Migration):
    """Simplify unique together field for comics."""

    dependencies = [
        ("codex", "0010_auto_20211117_0121"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_comics),
        migrations.AlterUniqueTogether(
            name="comic",
            unique_together={("library", "path")},
        ),
    ]
