# Generated by Django 3.0.5 on 2020-04-15 22:05

import codex.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('codex', '0012_auto_20200414_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmark', models.PositiveSmallIntegerField(null=True)),
                ('finished', models.BooleanField(default=False)),
                ('fit_to', models.CharField(choices=[('WIDTH', 'Width'), ('HEIGHT', 'Height'), ('ORIG', 'Original Size')], default=codex.models.FitToChoice['WIDTH'], max_length=6, null=True)),
                ('two_pages', models.BooleanField(default=False, null=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Comic')),
                ('session', models.ForeignKey(null=True, on_delete=codex.models.cascade_if_user_null, to='sessions.Session')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session', 'comic')},
            },
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
