"""Generated by Django 3.2.9 on 2021-12-06 01:10."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Folder name from BrowseGroup."""

    dependencies = [
        ("codex", "0012_auto_20211205_1859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
    ]
