"""Generated by Django 4.0.4 on 2022-04-22 00:46."""

from django.db import migrations, models

import codex.models


class Migration(migrations.Migration):
    """PDF and issue suffix support."""

    dependencies = [
        ("codex", "0013_int_issue_count_longer_charfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="file_format",
            field=models.CharField(
                default="comic",
                max_length=5,
                validators=[codex.models.validate_file_format_choice],
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="issue_suffix",
            field=models.CharField(db_index=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="comic",
            name="issue",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
