# Generated by Django 3.0.5 on 2020-04-15 22:59

import codex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('codex', '0013_auto_20200415_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='session',
            field=models.ForeignKey(default=1, on_delete=codex.models.cascade_if_user_null, to='sessions.Session'),
            preserve_default=False,
        ),
    ]
