"""Generated by Django 4.0.4 on 2022-04-22 22:19."""

from django.db import migrations, models

import codex.models


class Migration(migrations.Migration):
    """Remove sort_name. Add default ordering. Add pdf & issue_suffix."""

    dependencies = [
        ("codex", "0013_int_issue_count_longer_charfields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comic",
            options={
                "ordering": ("volume__name", "issue", "issue_suffix"),
                "verbose_name": "Issue",
            },
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="imprint",
            options={"ordering": ("publisher__name", "name")},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ("name",), "verbose_name_plural": "Series"},
        ),
        migrations.AlterModelOptions(
            name="volume",
            options={"ordering": ("series__name", "name")},
        ),
        migrations.RemoveField(
            model_name="comic",
            name="sort_name",
        ),
        migrations.RemoveField(
            model_name="failedimport",
            name="sort_name",
        ),
        migrations.RemoveField(
            model_name="folder",
            name="sort_name",
        ),
        migrations.RemoveField(
            model_name="imprint",
            name="sort_name",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="sort_name",
        ),
        migrations.RemoveField(
            model_name="series",
            name="sort_name",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="sort_name",
        ),
        migrations.AddField(
            model_name="comic",
            name="file_format",
            field=models.CharField(
                default="comic",
                max_length=5,
                validators=[codex.models.validate_file_format_choice],
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="issue_suffix",
            field=models.CharField(db_index=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="comic",
            name="issue",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
