"""Generated by Django 3.2.9 on 2021-12-06 01:51."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Failed Import becomes a fake browser group."""

    dependencies = [
        ("codex", "0013_alter_folder_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failedimport",
            name="reason",
        ),
        migrations.AddField(
            model_name="failedimport",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="failedimport",
            name="sort_name",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
    ]
