# Generated by Django 3.0.5 on 2020-04-16 00:23

import codex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('codex', '0015_auto_20200415_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='fit_to',
            field=models.CharField(choices=[('WIDTH', 'Width'), ('HEIGHT', 'Height'), ('ORIG', 'Original Size')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='session',
            field=models.ForeignKey(null=True, on_delete=codex.models.cascade_if_user_null, to='sessions.Session'),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='two_pages',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
