"""Generated by Django 4.0.6 on 2022-07-18 21:16."""

import os
import shutil

from pathlib import Path

from django.db import migrations


CONFIG_PATH = Path(__file__).parent.parent.parent / "config"
OLD_COVER_CACHE = CONFIG_PATH / "static"
CACHE_DIR = CONFIG_PATH / "cache"


def remove_old_caches(_apps, _schema_editor):
    """Clean up old cache locations."""
    print("Removing old cover cache...")
    shutil.rmtree(OLD_COVER_CACHE, ignore_errors=True)
    print("Removing old default cache...")
    for path in CACHE_DIR.iterdir():
        if path.suffix == ".djcache":
            path.unlink(missing_ok=True)
        elif str(path).endswith("_timestamp"):
            mtime = path.stat().st_mtime
            new_path = str(path).replace("_timestamp", ".timestamp")
            path = path.replace(new_path)
            os.utime(path, (mtime, mtime))


class Migration(migrations.Migration):
    """Remove comic.cover_path column."""

    dependencies = [
        ("codex", "0015_link_comics_to_top_level_folders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comic",
            name="cover_path",
        ),
        migrations.RunPython(remove_old_caches),
    ]
