# Generated by Django 3.1 on 2020-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0017_comic_cover_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover_path',
            field=models.CharField(default='codex/static/codex/default_cover.png', max_length=128),
        ),
    ]
