"""Generated by Django 4.1 on 2022-08-24 01:49."""

from django.conf import settings
from django.db import migrations, models

import codex.models


class Migration(migrations.Migration):
    """Rename Bookmark table."""

    dependencies = [
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("codex", "0017_alter_timestamp_options_alter_adminflag_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="UserBookmark", old_name="bookmark", new_name="page"
        ),
        migrations.RenameModel(
            old_name="UserBookmark",
            new_name="Bookmark",
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="fit_to",
            field=models.CharField(
                blank=True,
                default="",
                max_length=6,
                validators=[codex.models.validate_fit_to_choice],
            ),
        ),
    ]
