"""Generated by Django 4.1.4 on 2022-12-07 20:25."""

from django.db import migrations


class Migration(migrations.Migration):
    """Delete fake model used in Django Admin."""

    dependencies = [
        ("codex", "0018_rename_userbookmark_bookmark"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QueueJob",
        ),
    ]
