# Generated by Django 3.1 on 2020-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0018_auto_20200419_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover_path',
            field=models.CharField(default='codex/default_cover.png', max_length=128),
        ),
    ]
