# Generated by Django 3.1 on 2020-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0019_auto_20200419_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover_path',
            field=models.CharField(default='codex/default_cover.png', max_length=32),
        ),
    ]
