# Generated by Django 3.1 on 2020-04-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0021_auto_20200419_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='issue_count',
            new_name='volume_count',
        ),
    ]
