"""Generated by Django 4.1.7 on 2023-03-10 07:34."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("codex", "0021_bookmark_fit_to_choices_read_in_reverse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarianstatus",
            name="complete",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="librarianstatus",
            name="total",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="UserActive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bookmark",
            name="vertical",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
