"""Generated by Django 4.1.7 on 2023-03-02 02:55."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add vertical field to bookmark."""

    dependencies = [
        ("codex", "0021_bookmark_fit_to_choices_read_in_reverse"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="vertical",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
