"""Generated by Django 4.1.7 on 2023-03-08 23:55."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Allow nulls in Librarian Statuses."""

    dependencies = [
        ("codex", "0021_bookmark_fit_to_choices_read_in_reverse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarianstatus",
            name="complete",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="librarianstatus",
            name="total",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
