# Generated by Django 3.1 on 2020-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0022_auto_20200419_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='name',
        ),
        migrations.AddField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
