"""Generated by Django 4.1.7 on 2023-03-09 04:07."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Lasst active table."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("codex", "0022_alter_librarianstatus_complete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
