# Generated by Django 3.1 on 2020-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0024_auto_20200419_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='name_header',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='imprint',
            name='name_header',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='name_header',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
