# Generated by Django 3.1 on 2020-04-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0025_auto_20200419_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='display_name',
            new_name='sort_name',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='name_header',
        ),
        migrations.RemoveField(
            model_name='imprint',
            name='name_header',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='name_header',
        ),
        migrations.AddField(
            model_name='comic',
            name='sort_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='sort_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imprint',
            name='sort_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='sort_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='sort_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
