"""Generated by Django 5.0.4 on 2024-05-05 23:11."""

from django.db import migrations, models

from codex.models.const import ARTICLES

_GROUP_MODEL_NAMES = (
    "publisher",
    "imprint",
    "series",
    "storyarc",
    "folder",
    "comic",
    "failedimport",
)


def _set_lower_and_stored_sort_name(obj):
    """Create sort_name for model."""
    # Duplicate code from BaseGroupModel
    obj.lower_name = obj.name.lower()
    sort_name = ""
    name_parts = str(obj.lower_name).split()
    if len(name_parts) > 1:
        first_word = name_parts[0]
        if first_word in ARTICLES:
            sort_name = " ".join(name_parts[1:])
            sort_name += ", " + first_word
            obj.stored_sort_name = sort_name


def _generate_lower_and_stored_sort_name(apps, _schema_editor):
    """Update new stored_sort_name field."""
    for model_name in _GROUP_MODEL_NAMES:
        model = apps.get_model("codex", model_name)
        update_fields = ["lower_name", "stored_sort_name"]
        only_fields = ["name", *update_fields]
        update_groups = []
        objs = model.objects.only(*only_fields)
        for obj in objs:
            _set_lower_and_stored_sort_name(obj)
            if obj.stored_sort_name:
                update_groups.append(obj)
        if update_groups:
            model.objects.bulk_update(update_groups, update_fields)
            print(
                f"\tUpdated lower_name and stored_sort_name for {len(update_groups)} {model_name}s"
            )


class Migration(migrations.Migration):
    """Migrate."""

    dependencies = [
        ("codex", "0026_comicbox_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="failedimport",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="folder",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="imprint",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="publisher",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="series",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="storyarc",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="volume",
            name="lower_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="comic",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="failedimport",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="folder",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="imprint",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="publisher",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="series",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="storyarc",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="volume",
            name="stored_sort_name",
            field=models.CharField(db_index=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="adminflag",
            name="key",
            field=models.CharField(
                choices=[
                    ("FV", "Folder View"),
                    ("RG", "Registration"),
                    ("NU", "Non Users"),
                    ("AU", "Auto Update"),
                    ("SO", "Search Index Optimize"),
                    ("IM", "Import Metadata"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.RunPython(_generate_lower_and_stored_sort_name),
    ]
