# Generated by Django 3.1 on 2020-04-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0026_auto_20200419_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='folders',
            field=models.ManyToManyField(to='codex.Folder'),
        ),
        migrations.AddField(
            model_name='comic',
            name='imprint',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codex.imprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codex.publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='series',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codex.series'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comic',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_in', to='codex.folder'),
        ),
    ]
