"""Generated by Django 5.0.6 on 2024-07-02 21:01."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies: ClassVar[list] = [  # type: ignore
        ("codex", "0027_import_order_and_covers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminflag",
            name="key",
            field=models.CharField(
                choices=[
                    ("FV", "Folder View"),
                    ("RG", "Registration"),
                    ("NU", "Non Users"),
                    ("AU", "Auto Update"),
                    ("SO", "Search Index Optimize"),
                    ("IM", "Import Metadata"),
                    ("ST", "Send Telemetry"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="timestamp",
            name="key",
            field=models.CharField(
                choices=[
                    ("JA", "Janitor"),
                    ("VR", "Codex Version"),
                    ("SI", "Search Index UUID"),
                    ("AP", "API Key"),
                    ("TS", "Telemeter Sent"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
    ]
