# Generated by Django 3.1 on 2020-04-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0028_comic_comic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='comic',
        ),
    ]
