"""Generated by Django 5.0.6 on 2024-05-31 19:15."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0029_choices_adminflag_and_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="first_comic",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="codex.comic",
            ),
        ),
        migrations.AddField(
            model_name="imprint",
            name="first_comic",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="codex.comic",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="first_comic",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="codex.comic",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="first_comic",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="codex.comic",
            ),
        ),
        migrations.AddField(
            model_name="storyarc",
            name="first_comic",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="codex.comic",
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="first_comic",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="codex.comic",
            ),
        ),
    ]
