"""Generated by Django 5.1.2 on 2024-10-22 03:09."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0030_nocase_collation_day_month_indexes_status_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminflag",
            name="value",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="adminflag",
            name="key",
            field=models.CharField(
                choices=[
                    ("FV", "Folder View"),
                    ("RG", "Registration"),
                    ("NU", "Non Users"),
                    ("AU", "Auto Update"),
                    ("IM", "Import Metadata"),
                    ("ST", "Send Telemetry"),
                    ("BT", "Banner Text"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="timestamp",
            name="key",
            field=models.CharField(
                choices=[
                    ("AP", "API Key"),
                    ("VR", "Codex Version"),
                    ("JA", "Janitor"),
                    ("TS", "Telemeter Sent"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
    ]
