# Generated by Django 3.1 on 2020-04-22 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0030_comic_comic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self', to='codex.comic'),
        ),
    ]
