"""Generated by Django 5.1.3 on 2024-11-14 21:50."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0031_adminflag_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarianstatus",
            name="preactive",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
