"""Generated by Django 5.1.4 on 2024-12-21 03:50."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate DB."""

    dependencies = [
        ("codex", "0032_alter_librarianstatus_preactive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarianstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("CCC", "Create Covers"),
                    ("CCD", "Purge Covers"),
                    ("CFO", "Find Orphan"),
                    ("IAF", "Adopt Folders"),
                    ("ICC", "Covers Created"),
                    ("ICD", "Covers Deleted"),
                    ("ICL", "Covers Link"),
                    ("ICM", "Covers Moved"),
                    ("ICQ", "Query Missing Covers"),
                    ("ICU", "Covers Modified"),
                    ("IDD", "Dirs Deleted"),
                    ("IDM", "Dirs Moved"),
                    ("IDU", "Dirs Modified"),
                    ("IFC", "Files Created"),
                    ("IFD", "Files Deleted"),
                    ("IFI", "Failed Imports"),
                    ("IFM", "Files Moved"),
                    ("IFU", "Files Modified"),
                    ("IGU", "Group Update"),
                    ("IMC", "Link M2M Fields"),
                    ("IMQ", "Query M2M Fields"),
                    ("ITC", "Create Fks"),
                    ("ITQ", "Query Missing Fks"),
                    ("ITR", "Aggregate Tags"),
                    ("JCB", "Cleanup Bookmarks"),
                    ("JCD", "Cleanup Covers"),
                    ("JCR", "Codex Restart"),
                    ("JCS", "Codex Stop"),
                    ("JCU", "Codex Update"),
                    ("JDB", "Db Backup"),
                    ("JDO", "Db Optimize"),
                    ("JFC", "Fts Integrity Check"),
                    ("JFR", "Fts Rebuild"),
                    ("JIC", "Integrity Check"),
                    ("JIF", "Integrity Fk"),
                    ("JLV", "Codex Latest Version"),
                    ("JSD", "Cleanup Sessions"),
                    ("JTD", "Cleanup Fk"),
                    ("SIC", "Search Index Create"),
                    ("SID", "Search Index Remove"),
                    ("SIO", "Search Index Optimize"),
                    ("SIU", "Search Index Update"),
                    ("SIX", "Search Index Clear"),
                    ("WPO", "Poll"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
    ]
