"""Generated by Django 5.2.1 on 2025-05-13 00:07."""

from django.db import migrations

import codex.models.fields
import codex.models.library


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0033_alter_librarianstatus_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agerating",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="comic",
            name="community_rating",
            field=codex.models.fields.CoercingDecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="critical_rating",
            field=codex.models.fields.CoercingDecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="day",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="decade",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="file_type",
            field=codex.models.fields.CleaningCharField(
                blank=True,
                choices=[
                    ("CBZ", "Cbz"),
                    ("CBR", "Cbr"),
                    ("CBT", "Cbt"),
                    ("PDF", "Pdf"),
                ],
                db_collation="nocase",
                db_index=True,
                default="",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="issue_number",
            field=codex.models.fields.CoercingDecimalField(
                db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="issue_suffix",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="month",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="name",
            field=codex.models.fields.CleaningCharField(
                db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="notes",
            field=codex.models.fields.CleaningTextField(
                db_collation="nocase", default=""
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="page_count",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                db_index=True, default=0
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="path",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="comic",
            name="reading_direction",
            field=codex.models.fields.CleaningCharField(
                choices=[
                    ("ltr", "Ltr"),
                    ("rtl", "Rtl"),
                    ("ttb", "Ttb"),
                    ("btt", "Btt"),
                ],
                db_collation="nocase",
                db_index=True,
                default="ltr",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="review",
            field=codex.models.fields.CleaningTextField(
                db_collation="nocase", default=""
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="sort_name",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="summary",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", default=""
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="year",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contributorperson",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="contributorrole",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="customcover",
            name="path",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="failedimport",
            name="path",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=codex.models.fields.CleaningCharField(
                db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="path",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="folder",
            name="sort_name",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="nss",
            field=codex.models.fields.CleaningCharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="identifiertype",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="imprint",
            name="name",
            field=codex.models.fields.CleaningCharField(
                db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="imprint",
            name="sort_name",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="library",
            name="path",
            field=codex.models.fields.CleaningCharField(
                db_index=True,
                max_length=4095,
                unique=True,
                validators=[codex.models.library.validate_dir_exists],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="originalformat",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=codex.models.fields.CleaningCharField(
                db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="sort_name",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="scaninfo",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=codex.models.fields.CleaningCharField(
                db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="sort_name",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="volume_count",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="seriesgroup",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="story",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="storyarc",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="storyarc",
            name="sort_name",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="storyarcnumber",
            name="number",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="tagger",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=codex.models.fields.CleaningCharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="volume",
            name="issue_count",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="volume",
            name="name",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                db_index=True, default=None, null=True
            ),
        ),
    ]
