"""Generated by Django 5.2.2 on 2025-06-07 23:37."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0034_comicbox2_cleaning_fields_mtime_rename_identifiertype"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="identifier",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="creditrole",
            name="identifier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="codex.identifier",
            ),
        ),
        migrations.AddField(
            model_name="identifier",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("storyarc", "Arc"),
                    ("character", "Character"),
                    ("genre", "Genre"),
                    ("imprint", "Imprint"),
                    ("comic", "Issue"),
                    ("location", "Location"),
                    ("publisher", "Publisher"),
                    ("series", "Series"),
                    ("story", "Story"),
                    ("tag", "Tag"),
                    ("team", "Team"),
                    ("universe", "Universe"),
                    ("creditrole", "Role"),
                    ("creditperson", "Creator"),
                ],
                db_index=True,
                default="comic",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="librarianstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("CCC", "Create Covers"),
                    ("CCD", "Purge Covers"),
                    ("CFO", "Find Orphan"),
                    ("IAF", "Adopt Folders"),
                    ("ICC", "Create Custom Covers"),
                    ("ICD", "Remove Custom Covers"),
                    ("ICL", "Link Custom Covers"),
                    ("ICM", "Move Custom Covers"),
                    ("ICQ", "Query Missing Covers"),
                    ("ICU", "Update Custom Covers"),
                    ("IDD", "Remove Folders"),
                    ("IDM", "Move Folders"),
                    ("IDU", "Update Folders"),
                    ("IFC", "Create Comics"),
                    ("IFD", "Remove Comics"),
                    ("IFI", "Mark Failed Imports"),
                    ("IFM", "Move Comics"),
                    ("IFU", "Update Comics"),
                    ("IGU", "Update Group Timestamps"),
                    ("IMC", "Link Comics To Tags"),
                    ("IPL", "Prepare Tag Links"),
                    ("IRT", "Read Tags"),
                    ("ITC", "Create Tags"),
                    ("ITQ", "Query Missing Tags"),
                    ("ITR", "Aggregate Tags"),
                    ("ITU", "Update Tags"),
                    ("JCB", "Cleanup Bookmarks"),
                    ("JCD", "Cleanup Covers"),
                    ("JCR", "Codex Restart"),
                    ("JCS", "Codex Stop"),
                    ("JCU", "Codex Update"),
                    ("JDB", "Db Backup"),
                    ("JDO", "Db Optimize"),
                    ("JFC", "Fts Integrity Check"),
                    ("JFR", "Fts Rebuild"),
                    ("JIC", "Integrity Check"),
                    ("JIF", "Integrity Fk"),
                    ("JLV", "Codex Latest Version"),
                    ("JSD", "Cleanup Sessions"),
                    ("JTD", "Cleanup Fk"),
                    ("SIC", "Search Index Create"),
                    ("SID", "Search Index Remove"),
                    ("SIO", "Search Index Optimize"),
                    ("SIU", "Search Index Update"),
                    ("SIX", "Search Index Clear"),
                    ("WPO", "Poll"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="character",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="creditperson",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="genre",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="identifier",
            unique_together={("source", "id_type", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="story",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="storyarc",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="universe",
            unique_together={("name",)},
        ),
    ]
