"""Generated by Django 5.2.1 on 2025-05-13 08:35."""

from django.db import migrations


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0034_alter_agerating_name_alter_character_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contributor",
            new_name="Credit",
        ),
        migrations.RenameModel(
            old_name="ContributorPerson",
            new_name="CreditPerson",
        ),
        migrations.RenameModel(
            old_name="ContributorRole",
            new_name="CreditRole",
        ),
        migrations.RenameField(
            model_name="comic",
            old_name="contributors",
            new_name="credits",
        ),
    ]
