"""Generated by Django 5.2.1 on 2025-05-22 23:48."""

from django.db import migrations

import codex.models.fields


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0034_comicbox2_cleaning_fields_mtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comic",
            name="community_rating",
        ),
        migrations.AddField(
            model_name="comic",
            name="collection_title",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", db_index=True, default="", max_length=16
            ),
        ),
    ]
