"""Generated by Django 5.2.8 on 2025-11-24 02:28."""

from django.db import migrations, models

import codex.models.library


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0035_fts_optmize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="path",
            field=models.CharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="customcover",
            name="path",
            field=models.CharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="failedimport",
            name="path",
            field=models.CharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="folder",
            name="path",
            field=models.CharField(db_index=True, max_length=4095),
        ),
        migrations.AlterField(
            model_name="library",
            name="path",
            field=models.CharField(
                db_index=True,
                max_length=4095,
                unique=True,
                validators=[codex.models.library.validate_dir_exists],
            ),
        ),
    ]
