"""Generated by Django 5.2.10 on 2026-01-29 22:05."""

from django.db import migrations, models

import codex.models.fields


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0036_alter_comic_path_alter_customcover_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="reading_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rtl", "Rtl"),
                    ("ltr", "Ltr"),
                    ("ttb", "Ttb"),
                    ("btt", "Btt"),
                ],
                default="",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="file_type",
            field=codex.models.fields.CleaningCharField(
                blank=True,
                choices=[
                    ("CBZ", "Cbz"),
                    ("CBR", "Cbr"),
                    ("CB7", "Cb7"),
                    ("CBT", "Cbt"),
                    ("PDF", "Pdf"),
                ],
                db_collation="nocase",
                db_index=True,
                default="",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="reading_direction",
            field=codex.models.fields.CleaningCharField(
                choices=[
                    ("rtl", "Rtl"),
                    ("ltr", "Ltr"),
                    ("ttb", "Ttb"),
                    ("btt", "Btt"),
                ],
                db_collation="nocase",
                db_index=True,
                default="ltr",
                max_length=3,
            ),
        ),
    ]
