"""Generated by Django 5.2.3 on 2025-06-20 08:01."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0036_alter_librarianstatus_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarianstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("CCC", "Create Covers"),
                    ("CCD", "Purge Covers"),
                    ("CFO", "Find Orphan Covers"),
                    ("IAF", "Adopt Folders"),
                    ("ICC", "Create Custom Covers"),
                    ("ICD", "Remove Custom Covers"),
                    ("ICL", "Link Custom Covers"),
                    ("ICM", "Move Custom Covers"),
                    ("ICQ", "Query Missing Covers"),
                    ("ICU", "Update Custom Covers"),
                    ("IDD", "Remove Folders"),
                    ("IDM", "Move Folders"),
                    ("IFC", "Create Comics"),
                    ("IFD", "Remove Comics"),
                    ("IFI", "Mark Failed Imports"),
                    ("IFM", "Move Comics"),
                    ("IFU", "Update Comics"),
                    ("IGU", "Update Group Timestamps"),
                    ("ILT", "Link Comics To Tags"),
                    ("IQL", "Query Tag Links"),
                    ("IQT", "Query Missing Tags"),
                    ("IQU", "Query Comic Updates"),
                    ("IRT", "Read Tags"),
                    ("ITC", "Create Tags"),
                    ("ITR", "Aggregate Tags"),
                    ("ITU", "Update Tags"),
                    ("JCB", "Cleanup Bookmarks"),
                    ("JCD", "Cleanup Covers"),
                    ("JCR", "Codex Restart"),
                    ("JCS", "Codex Stop"),
                    ("JCU", "Codex Update"),
                    ("JDB", "Db Backup"),
                    ("JDO", "Db Optimize"),
                    ("JFC", "Fts Integrity Check"),
                    ("JFR", "Fts Rebuild"),
                    ("JIC", "Integrity Check"),
                    ("JIF", "Integrity Fk"),
                    ("JLV", "Codex Latest Version"),
                    ("JSD", "Cleanup Sessions"),
                    ("JTD", "Cleanup Fk"),
                    ("SIC", "Search Index Create"),
                    ("SID", "Search Index Remove"),
                    ("SIO", "Search Index Optimize"),
                    ("SIU", "Search Index Update"),
                    ("SIX", "Search Index Clear"),
                    ("WPO", "Poll"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
    ]
