"""Generated by Django 5.2.1 on 2025-05-15 00:52."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0036_recreate_comicfts"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="metadata_mtime",
            field=models.DateTimeField(null=True),
        ),
    ]
