"""Generated by Django 5.2.3 on 2025-06-23 07:09."""

from django.db import migrations

import codex.models.fields


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0037_alter_librarianstatus_status_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="volume",
            name="number_to",
            field=codex.models.fields.CoercingPositiveSmallIntegerField(
                db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="imprint",
            unique_together={("publisher", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("imprint", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together={("series", "name", "number_to")},
        ),
    ]
