"""Generated by Django 6.0.3 on 2026-03-30 06:33."""

from importlib import import_module

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import codex.models.settings

# Session keys to migrate and their target model / client value.
_MIGRATIONS = (
    ("browser", "settingsbrowser", "api"),
    ("reader", "settingsreader", "api"),
    ("opds_browser", "settingsbrowser", "opds"),
    ("opds_reader", "settingsreader", "opds"),
)
_BROWSER_DIRECT_KEYS = frozenset(
    {
        "top_group",
        "order_by",
        "order_reverse",
        "custom_covers",
        "dynamic_covers",
        "twenty_four_hour_time",
        "always_show_filename",
    }
)
_READER_DIRECT_KEYS = frozenset(
    {
        "fit_to",
        "two_pages",
        "reading_direction",
        "read_rtl_in_reverse",
        "finish_on_last_page",
        "page_transition",
        "cache_book",
    }
)
_FILTER_KEYS = frozenset(
    {
        "bookmark",
        "age_rating",
        "characters",
        "country",
        "credits",
        "critical_rating",
        "decade",
        "file_type",
        "genres",
        "identifier_source",
        "language",
        "locations",
        "monochrome",
        "original_format",
        "reading_direction",
        "series_groups",
        "stories",
        "story_arcs",
        "tagger",
        "tags",
        "teams",
        "universes",
        "year",
    }
)
_SHOW_KEYS = ("p", "i", "s", "v")


def create_default_show_row(apps, _schema_editor):
    """Create the default model."""
    show_model = apps.get_model("codex", "SettingsBrowserShow")
    show_model.objects.create(pk=1)


def _get_or_create_show(show_model, show_dict):
    """Get or create a SettingsBrowserShow row from a show dict."""
    show_kwargs = {k: bool(show_dict.get(k, k in {"p", "s"})) for k in _SHOW_KEYS}
    show, _ = show_model.objects.get_or_create(**show_kwargs)
    return show


def _create_browser_filters(filters_model, browser, settings_dict):
    """Create a SettingsBrowserFilters row from the session settings dict."""
    filters_dict = settings_dict.get("filters", {})
    kwargs = {"browser": browser}
    for key in _FILTER_KEYS:
        if key in filters_dict:
            value = filters_dict[key]
            kwargs[key] = value if key == "bookmark" else (list(value) if value else [])
    # Legacy "bookmark_filter" key at the top level.
    if "bookmark_filter" in settings_dict and "bookmark" not in kwargs:
        kwargs["bookmark"] = settings_dict["bookmark_filter"]
    filters_model.objects.create(**kwargs)


def _create_browser_last_route(route_model, browser, settings_dict):
    """Create a SettingsBrowserLastRoute row from the session settings dict."""
    route_dict = settings_dict.get("last_route", {})
    kwargs = {"browser": browser}
    if "group" in route_dict:
        kwargs["group"] = route_dict["group"]
    if "pks" in route_dict:
        pks = route_dict["pks"]
        kwargs["pks"] = list(pks) if pks else [0]
    if "page" in route_dict:
        kwargs["page"] = route_dict["page"]
    route_model.objects.create(**kwargs)


def _migrate_browser_session(settings_dict, model_map, client, user, session_key):
    """Migrate one browser session dict into the new related-model tables."""
    browser_model = model_map["settingsbrowser"]
    scope_filter = {"client": client, "name": ""}

    existing = None
    if user:
        existing = browser_model.objects.filter(user=user, **scope_filter).first()
    if existing is None:
        existing = browser_model.objects.filter(
            session_id=session_key,
            **scope_filter,
        ).first()
    if existing is not None:
        return True

    # Show — get or create the shared row.
    show_dict = settings_dict.get("show", {})
    show = _get_or_create_show(model_map["settingsbrowsershow"], show_dict)

    # Browser — direct fields only.
    create_kwargs = {
        "user": user,
        "session_id": session_key,
        "show": show,
        **scope_filter,
    }
    for key in _BROWSER_DIRECT_KEYS:
        if key in settings_dict:
            create_kwargs[key] = settings_dict[key]
    for key in ("q", "search"):
        if key in settings_dict:
            create_kwargs["search"] = settings_dict[key]
            break
    browser = browser_model.objects.create(**create_kwargs)

    # Filters and last route — one-to-one children.
    _create_browser_filters(model_map["settingsbrowserfilters"], browser, settings_dict)
    _create_browser_last_route(
        model_map["settingsbrowserlastroute"],
        browser,
        settings_dict,
    )
    return True


def _migrate_reader_session(settings_dict, model_map, client, user, session_key):
    """Migrate one reader session dict into the SettingsReader table."""
    model = model_map["settingsreader"]
    scope_filter = {"client": client, "comic": None, "series": None, "folder": None}

    existing = None
    if user:
        existing = model.objects.filter(user=user, **scope_filter).first()
    if existing is None:
        existing = model.objects.filter(
            session_id=session_key,
            **scope_filter,
        ).first()
    if existing is not None:
        return True

    create_kwargs = {"user": user, "session_id": session_key, **scope_filter}
    for key in _READER_DIRECT_KEYS:
        if key in settings_dict:
            create_kwargs[key] = settings_dict[key]
    model.objects.create(**create_kwargs)
    return True


_MIGRATE_FN_MAP = {
    "settingsbrowser": _migrate_browser_session,
    "settingsreader": _migrate_reader_session,
}


def _get_user(user_model, session_data):
    """Resolve the authenticated user from session data, or None."""
    user_id = session_data.get("_auth_user_id")
    if user_id is None:
        return None
    try:
        return user_model.objects.get(pk=user_id)
    except user_model.DoesNotExist:
        return None


def migrate_session_forward_model(
    session_data, data_key, model_map, model_name, client, user, session_key
) -> bool:
    """Read settings from one Django session and populate the new tables."""
    settings_dict = session_data.get(data_key)
    if not settings_dict:
        return False

    migrate_fn = _MIGRATE_FN_MAP[model_name]
    return migrate_fn(settings_dict, model_map, client, user, session_key)


def migrate_session_forward(
    db_session, user_model, model_map, encoder, migrated, cleaned
) -> tuple[int, int]:
    """Read settings from one Django session and populate the new tables."""
    session_data = db_session.get_decoded()
    if not session_data:
        return migrated, cleaned

    user = _get_user(user_model, session_data)
    session_key = db_session.session_key
    any_migrated = False

    for data_key, model_name, client in _MIGRATIONS:
        if migrate_session_forward_model(
            session_data, data_key, model_map, model_name, client, user, session_key
        ):
            any_migrated = True
            migrated += 1

    if any_migrated:
        changed = False
        for data_key, _model_name, _client in _MIGRATIONS:
            if data_key in session_data:
                del session_data[data_key]
                changed = True
        if changed:
            db_session.session_data = encoder.encode(session_data)
            db_session.save(update_fields=["session_data"])
            cleaned += 1
    return migrated, cleaned


def migrate_sessions_forward(apps, _schema_editor):
    """Read settings from every Django session and populate the new tables."""
    from django.contrib.sessions.models import Session

    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    model_map = {
        "settingsbrowser": apps.get_model("codex", "SettingsBrowser"),
        "settingsreader": apps.get_model("codex", "SettingsReader"),
        "settingsbrowsershow": apps.get_model("codex", "SettingsBrowserShow"),
        "settingsbrowserfilters": apps.get_model("codex", "SettingsBrowserFilters"),
        "settingsbrowserlastroute": apps.get_model("codex", "SettingsBrowserLastRoute"),
    }

    session_store = import_module(settings.SESSION_ENGINE).SessionStore
    encoder = session_store()

    sessions = Session.objects.order_by("-expire_date")
    migrated = 0
    cleaned = 0

    for db_session in sessions.iterator():
        migrated, cleaned = migrate_session_forward(
            db_session, user_model, model_map, encoder, migrated, cleaned
        )


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0037_redefine_reading_direction_filetype_choices"),
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarianstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("CCC", "Create Covers"),
                    ("CFO", "Find Orphan Covers"),
                    ("CRC", "Remove Covers"),
                    ("IAT", "Aggregate Tags From Comics"),
                    ("ICC", "Create Comics"),
                    ("ICT", "Create Tags"),
                    ("ICV", "Create Custom Covers"),
                    ("IFC", "Mark Failed Failed Imports"),
                    ("IFD", "Clean Up Failed Imports"),
                    ("IFQ", "Query Failed Imports"),
                    ("IFU", "Update Failed Imports"),
                    ("IGU", "Update Timestamps For Browser Groups"),
                    ("ILT", "Link Tags"),
                    ("ILV", "Link Custom Covers"),
                    ("IQC", "Query Comics"),
                    ("IQL", "Query Tag Links"),
                    ("IQT", "Query Missing Tags"),
                    ("IQV", "Query Missing Custom Covers"),
                    ("IRC", "Remove Comics"),
                    ("IRF", "Remove Folders"),
                    ("IRT", "Read Tags From Comics"),
                    ("IRV", "Remove Custom Covers"),
                    ("ISC", "Create Search Index Entries"),
                    ("ISU", "Update Search Index Entries"),
                    ("IUC", "Update Comics"),
                    ("IUT", "Update Tags"),
                    ("IUV", "Update Custom Covers"),
                    ("JAF", "Adopt Orphan Folders"),
                    ("JAS", "Cleanup Orphan Settings"),
                    ("JCT", "Cleanup Orphan Tags"),
                    ("JCU", "Update Codex Server Software"),
                    ("JDB", "Backup Database"),
                    ("JDO", "Optimize Database"),
                    ("JID", "Check Integrity Of Entire Database"),
                    ("JIF", "Check Integrtity Of Database Foreign Keys"),
                    ("JIS", "Check Integrity Of Full Text Virtual Table"),
                    ("JLV", "Check Codex Latest Version"),
                    ("JRB", "Cleanup Orphan Bookmarks"),
                    ("JRS", "Cleanup Old Sessions"),
                    ("JRV", "Cleanup Orphan Covers"),
                    ("JSR", "Rebuild Full Text Search Virtual Table"),
                    ("RCR", "Restart Codex Server"),
                    ("RCS", "Stop Codex Server"),
                    ("SIO", "Optimize Search Virtual Table"),
                    ("SIR", "Clean Orphan Search Entries"),
                    ("SIX", "Clear Full Text Search Table"),
                    ("SSC", "Sync New Search Entries"),
                    ("SSU", "Sync Old Search Entries"),
                    ("WPO", "Poll Library"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="SettingsReader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.CharField(
                        choices=[("api", "API"), ("opds", "OPDS")],
                        db_index=True,
                        default="api",
                        max_length=4,
                    ),
                ),
                (
                    "fit_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Screen"),
                            ("W", "Width"),
                            ("H", "Height"),
                            ("O", "Orig"),
                        ],
                        default="",
                        max_length=1,
                    ),
                ),
                ("two_pages", models.BooleanField(default=None, null=True)),
                (
                    "reading_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rtl", "Rtl"),
                            ("ltr", "Ltr"),
                            ("ttb", "Ttb"),
                            ("btt", "Btt"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                ("read_rtl_in_reverse", models.BooleanField(default=None, null=True)),
                ("finish_on_last_page", models.BooleanField(default=None, null=True)),
                ("page_transition", models.BooleanField(default=None, null=True)),
                ("cache_book", models.BooleanField(default=None, null=True)),
                (
                    "comic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codex.comic",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="codex.folder",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codex.series",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=codex.models.settings.cascade_if_user_null,
                        to="sessions.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=codex.models.settings.cascade_if_session_null,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "reader settings",
                "get_latest_by": "updated_at",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("comic__isnull", True),
                                ("folder__isnull", True),
                                ("series__isnull", True),
                            ),
                            models.Q(
                                ("comic__isnull", False),
                                ("folder__isnull", True),
                                ("series__isnull", True),
                            ),
                            models.Q(
                                ("comic__isnull", True),
                                ("folder__isnull", True),
                                ("series__isnull", False),
                            ),
                            models.Q(
                                ("comic__isnull", True),
                                ("folder__isnull", False),
                                ("series__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="settingsreader_scope_xor",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("user__isnull", False),
                            ("comic__isnull", True),
                            ("folder__isnull", True),
                            ("series__isnull", True),
                        ),
                        fields=("user", "client"),
                        name="unique_settingsreader_user_global",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("session__isnull", False),
                            ("comic__isnull", True),
                            ("folder__isnull", True),
                            ("series__isnull", True),
                        ),
                        fields=("session", "client"),
                        name="unique_settingsreader_session_global",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("comic__isnull", False), ("user__isnull", False)
                        ),
                        fields=("user", "client", "comic"),
                        name="unique_settingsreader_user_comic",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("comic__isnull", False), ("session__isnull", False)
                        ),
                        fields=("session", "client", "comic"),
                        name="unique_settingsreader_session_comic",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("series__isnull", False), ("user__isnull", False)
                        ),
                        fields=("user", "client", "series"),
                        name="unique_settingsreader_user_series",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("series__isnull", False), ("session__isnull", False)
                        ),
                        fields=("session", "client", "series"),
                        name="unique_settingsreader_session_series",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("folder__isnull", False), ("user__isnull", False)
                        ),
                        fields=("user", "client", "folder"),
                        name="unique_settingsreader_user_folder",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("folder__isnull", False), ("session__isnull", False)
                        ),
                        fields=("session", "client", "folder"),
                        name="unique_settingsreader_session_folder",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SettingsBrowser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.CharField(
                        choices=[("api", "API"), ("opds", "OPDS")],
                        db_index=True,
                        default="api",
                        max_length=4,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "top_group",
                    models.CharField(
                        choices=[
                            ("p", "Publishers"),
                            ("i", "Imprints"),
                            ("s", "Series"),
                            ("v", "Volumes"),
                            ("c", "Issues"),
                            ("f", "Folders"),
                            ("a", "Story Arcs"),
                        ],
                        default="p",
                        max_length=1,
                    ),
                ),
                (
                    "order_by",
                    models.CharField(
                        choices=[
                            ("created_at", "Added Time"),
                            ("age_rating", "Age Rating"),
                            ("child_count", "Child Count"),
                            ("critical_rating", "Critical Rating"),
                            ("filename", "Filename"),
                            ("size", "File Size"),
                            ("bookmark_updated_at", "Last Read"),
                            ("sort_name", "Name"),
                            ("page_count", "Page Count"),
                            ("date", "Publish Date"),
                            ("search_score", "Search Score"),
                            ("story_arc_number", "Story Arc Number"),
                            ("updated_at", "Updated Time"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("order_reverse", models.BooleanField(default=False)),
                ("search", models.CharField(blank=True, default="", max_length=4095)),
                ("custom_covers", models.BooleanField(default=True)),
                ("dynamic_covers", models.BooleanField(default=True)),
                ("twenty_four_hour_time", models.BooleanField(default=False)),
                ("always_show_filename", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=codex.models.settings.cascade_if_user_null,
                        to="sessions.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=codex.models.settings.cascade_if_session_null,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "browser settings",
                "get_latest_by": "updated_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "client", "name"),
                        name="unique_settingsbrowser_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session__isnull", False)),
                        fields=("session", "client", "name"),
                        name="unique_settingsbrowser_session",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SettingsBrowserFilters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bookmark",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "All"),
                            ("IN_PROGRESS", "In Progress"),
                            ("READ", "Read"),
                            ("UNREAD", "Unread"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("age_rating", models.JSONField(default=list)),
                ("characters", models.JSONField(default=list)),
                ("country", models.JSONField(default=list)),
                ("credits", models.JSONField(default=list)),
                ("critical_rating", models.JSONField(default=list)),
                ("decade", models.JSONField(default=list)),
                ("file_type", models.JSONField(default=list)),
                ("genres", models.JSONField(default=list)),
                ("identifier_source", models.JSONField(default=list)),
                ("language", models.JSONField(default=list)),
                ("locations", models.JSONField(default=list)),
                ("monochrome", models.JSONField(default=list)),
                ("original_format", models.JSONField(default=list)),
                ("reading_direction", models.JSONField(default=list)),
                ("series_groups", models.JSONField(default=list)),
                ("stories", models.JSONField(default=list)),
                ("story_arcs", models.JSONField(default=list)),
                ("tagger", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("teams", models.JSONField(default=list)),
                ("universes", models.JSONField(default=list)),
                ("year", models.JSONField(default=list)),
                (
                    "browser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="codex.settingsbrowser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "browser filter settings",
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SettingsBrowserLastRoute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("p", "Publishers"),
                            ("i", "Imprints"),
                            ("s", "Series"),
                            ("v", "Volumes"),
                            ("c", "Issues"),
                            ("f", "Folders"),
                            ("a", "Story Arcs"),
                            ("r", "Root"),
                        ],
                        default="r",
                        max_length=1,
                    ),
                ),
                ("pks", models.JSONField(default=list)),
                ("page", models.PositiveSmallIntegerField(default=1)),
                (
                    "browser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_route",
                        to="codex.settingsbrowser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "browser last-route settings",
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SettingsBrowserShow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("p", models.BooleanField(default=True)),
                ("i", models.BooleanField(default=False)),
                ("s", models.BooleanField(default=True)),
                ("v", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "browser show settings",
                "get_latest_by": "updated_at",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("p", "i", "s", "v"),
                        name="unique_settingsbrowsershow_flags",
                    )
                ],
            },
        ),
        migrations.RunPython(
            code=create_default_show_row,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="settingsbrowser",
            name="show",
            field=models.ForeignKey(
                # Created by RunPython above.
                default=1,  # ty: ignore[invalid-argument-type]
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="codex.settingsbrowsershow",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=migrate_sessions_forward,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="fit_to",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="reading_direction",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="two_pages",
        ),
        migrations.AlterField(
            model_name="librarianstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("CCC", "Create Covers"),
                    ("CFO", "Find Orphan Covers"),
                    ("CRC", "Remove Covers"),
                    ("IAT", "Aggregate Tags From Comics"),
                    ("ICC", "Create Comics"),
                    ("ICT", "Create Tags"),
                    ("ICV", "Create Custom Covers"),
                    ("IFC", "Mark Failed Failed Imports"),
                    ("IFD", "Clean Up Failed Imports"),
                    ("IFQ", "Query Failed Imports"),
                    ("IFU", "Update Failed Imports"),
                    ("IGU", "Update Timestamps For Browser Groups"),
                    ("ILT", "Link Tags"),
                    ("ILV", "Link Custom Covers"),
                    ("IQC", "Query Comics"),
                    ("IQL", "Query Tag Links"),
                    ("IQT", "Query Missing Tags"),
                    ("IQV", "Query Missing Custom Covers"),
                    ("IRC", "Remove Comics"),
                    ("IRF", "Remove Folders"),
                    ("IRT", "Read Tags From Comics"),
                    ("IRV", "Remove Custom Covers"),
                    ("ISC", "Create Search Index Entries"),
                    ("ISU", "Update Search Index Entries"),
                    ("IUC", "Update Comics"),
                    ("IUT", "Update Tags"),
                    ("IUV", "Update Custom Covers"),
                    ("JAF", "Adopt Orphan Folders"),
                    ("JAS", "Cleanup Orphan Settings"),
                    ("JCT", "Cleanup Orphan Tags"),
                    ("JCU", "Update Codex Server Software"),
                    ("JDB", "Backup Database"),
                    ("JDO", "Optimize Database"),
                    ("JID", "Check Integrity Of Entire Database"),
                    ("JIF", "Check Integrtity Of Database Foreign Keys"),
                    ("JIS", "Check Integrity Of Full Text Virtual Table"),
                    ("JLV", "Check Codex Latest Version"),
                    ("JRB", "Cleanup Orphan Bookmarks"),
                    ("JRS", "Cleanup Old Sessions"),
                    ("JRV", "Cleanup Orphan Covers"),
                    ("JSR", "Rebuild Full Text Search Virtual Table"),
                    ("RCR", "Restart Codex Server"),
                    ("RCS", "Stop Codex Server"),
                    ("SIO", "Optimize Search Virtual Table"),
                    ("SIR", "Clean Orphan Search Entries"),
                    ("SIX", "Clear Full Text Search Table"),
                    ("SSC", "Sync New Search Entries"),
                    ("SSU", "Sync Old Search Entries"),
                    ("WPO", "Poll Library"),
                    ("WRS", "Restart File Watcher"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="settingsreader",
            name="settingsreader_scope_xor",
        ),
        migrations.RemoveConstraint(
            model_name="settingsreader",
            name="unique_settingsreader_user_global",
        ),
        migrations.RemoveConstraint(
            model_name="settingsreader",
            name="unique_settingsreader_session_global",
        ),
        migrations.AddField(
            model_name="settingsreader",
            name="story_arc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="codex.storyarc",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsreader",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("comic__isnull", True),
                        ("folder__isnull", True),
                        ("series__isnull", True),
                        ("story_arc__isnull", True),
                    ),
                    models.Q(
                        ("comic__isnull", False),
                        ("folder__isnull", True),
                        ("series__isnull", True),
                        ("story_arc__isnull", True),
                    ),
                    models.Q(
                        ("comic__isnull", True),
                        ("folder__isnull", True),
                        ("series__isnull", False),
                        ("story_arc__isnull", True),
                    ),
                    models.Q(
                        ("comic__isnull", True),
                        ("folder__isnull", False),
                        ("series__isnull", True),
                        ("story_arc__isnull", True),
                    ),
                    models.Q(
                        ("comic__isnull", True),
                        ("folder__isnull", True),
                        ("series__isnull", True),
                        ("story_arc__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="settingsreader_scope_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsreader",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    ("comic__isnull", True),
                    ("folder__isnull", True),
                    ("series__isnull", True),
                    ("story_arc__isnull", True),
                ),
                fields=("user", "client"),
                name="unique_settingsreader_user_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsreader",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session__isnull", False),
                    ("comic__isnull", True),
                    ("folder__isnull", True),
                    ("series__isnull", True),
                    ("story_arc__isnull", True),
                ),
                fields=("session", "client"),
                name="unique_settingsreader_session_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsreader",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("story_arc__isnull", False), ("user__isnull", False)
                ),
                fields=("user", "client", "story_arc"),
                name="unique_settingsreader_user_story_arc",
            ),
        ),
        migrations.AddConstraint(
            model_name="settingsreader",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session__isnull", False), ("story_arc__isnull", False)
                ),
                fields=("session", "client", "story_arc"),
                name="unique_settingsreader_session_story_arc",
            ),
        ),
    ]
