# Generated by Django 6.0.4 on 2026-04-20 21:43
"""
Add Comic.metron_age_rating and GroupAuth.metron_age_rating.

Also backfills Comic.metron_age_rating from the existing age_rating FK
via comicbox's ``to_metron_age_rating()``, and seeds the new
``AGE_RATING_DEFAULT`` admin flag with ``Adult`` (most-secure default).
"""

from comicbox.enums.maps.age_rating import to_metron_age_rating
from comicbox.enums.metroninfo import MetronAgeRatingEnum
from django.db import migrations, models

import codex.models.fields

_AR_FLAG_KEY = "AR"
_DEFAULT_RATING = MetronAgeRatingEnum.ADULT.value
_CHUNK = 500


def _backfill_metron_age_rating(apps, _schema_editor) -> None:
    """Convert existing Comic.age_rating.name values to Comic.metron_age_rating."""
    comic_model = apps.get_model("codex", "comic")
    qs = (
        comic_model.objects.filter(age_rating__isnull=False)
        .select_related("age_rating")
        .only("pk", "age_rating__name")
    )
    to_update = []
    for comic in qs.iterator(chunk_size=_CHUNK):
        result = to_metron_age_rating(comic.age_rating.name)
        if result is None:
            continue
        comic.metron_age_rating = result.value
        to_update.append(comic)
    if to_update:
        comic_model.objects.bulk_update(
            to_update, ["metron_age_rating"], batch_size=_CHUNK
        )


def _seed_age_rating_default_flag(apps, _schema_editor) -> None:
    """Seed AGE_RATING_DEFAULT flag with Adult (most-secure default)."""
    admin_flag_model = apps.get_model("codex", "adminflag")
    flag, _created = admin_flag_model.objects.get_or_create(
        key=_AR_FLAG_KEY,
        defaults={"value": _DEFAULT_RATING},
    )
    if not flag.value:
        # Upgrade case: row pre-seeded by app init with value="".
        flag.value = _DEFAULT_RATING
        flag.save(update_fields=["value"])


def _noop(_apps, _schema_editor) -> None:
    """Reverse no-op (data migrations stay applied on rollback)."""


class Migration(migrations.Migration):
    """Add Metron age rating to Comic and GroupAuth, seed AGE_RATING_DEFAULT."""

    dependencies = [
        ("codex", "0038_settings_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="metron_age_rating",
            field=codex.models.fields.CleaningCharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("Everyone", "Everyone"),
                    ("Teen", "Teen"),
                    ("Teen Plus", "Teen Plus"),
                    ("Mature", "Mature"),
                    ("Explicit", "Explicit"),
                    ("Adult", "Adult"),
                ],
                db_collation="nocase",
                db_index=True,
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupauth",
            name="metron_age_rating",
            field=codex.models.fields.CleaningCharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("Everyone", "Everyone"),
                    ("Teen", "Teen"),
                    ("Teen Plus", "Teen Plus"),
                    ("Mature", "Mature"),
                    ("Explicit", "Explicit"),
                    ("Adult", "Adult"),
                ],
                db_collation="nocase",
                db_index=True,
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adminflag",
            name="key",
            field=models.CharField(
                choices=[
                    ("AR", "Age Rating Default"),
                    ("AU", "Auto Update"),
                    ("BT", "Banner Text"),
                    ("FV", "Folder View"),
                    ("IM", "Import Metadata"),
                    ("LI", "Lazy Import Metadata"),
                    ("NU", "Non Users"),
                    ("RG", "Registration"),
                    ("ST", "Send Telemetry"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.RunPython(_backfill_metron_age_rating, _noop),
        migrations.RunPython(_seed_age_rating_default_flag, _noop),
    ]
