# Generated by Django 5.2.3 on 2025-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0038_alter_volume_unique_together_volume_number_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianstatus',
            name='status_type',
            field=models.CharField(choices=[('CCC', 'Create Covers'), ('CCD', 'Purge Covers'), ('CFO', 'Find Orphan Covers'), ('ICC', 'Create Custom Covers'), ('ICD', 'Remove Custom Covers'), ('ICL', 'Link Custom Covers'), ('ICM', 'Move Custom Covers'), ('ICQ', 'Query Missing Covers'), ('ICU', 'Update Custom Covers'), ('IDD', 'Remove Folders'), ('IDM', 'Move Folders'), ('IFC', 'Create Comics'), ('IFD', 'Remove Comics'), ('IFI', 'Mark Failed Imports'), ('IFM', 'Move Comics'), ('IFU', 'Update Comics'), ('IGU', 'Update Group Timestamps'), ('ILT', 'Link Comics To Tags'), ('IQL', 'Query Tag Links'), ('IQT', 'Query Missing Tags'), ('IQU', 'Query Comic Updates'), ('IRT', 'Read Tags'), ('ITC', 'Create Tags'), ('ITR', 'Aggregate Tags'), ('ITU', 'Update Tags'), ('JAF', 'Adopt Orphan Folders'), ('JCB', 'Cleanup Bookmarks'), ('JCD', 'Cleanup Covers'), ('JCU', 'Codex Update'), ('JDB', 'Db Backup'), ('JDO', 'Db Optimize'), ('JFC', 'Fts Integrity Check'), ('JFR', 'Fts Rebuild'), ('JIC', 'Integrity Check'), ('JIF', 'Integrity Fk'), ('JLV', 'Codex Latest Version'), ('JSD', 'Cleanup Sessions'), ('JTR', 'Cleanup Tags'), ('RCR', 'Codex Restart'), ('RCS', 'Codex Stop'), ('SIC', 'Search Index Create'), ('SID', 'Search Index Remove'), ('SIO', 'Search Index Optimize'), ('SIU', 'Search Index Update'), ('SIX', 'Search Index Clear'), ('WPO', 'Poll')], db_index=True, max_length=3),
        ),
    ]
