# Generated by Django 6.0.4 on 2026-04-20 21:43
"""
Consolidate Metron-normalized age-rating metadata on ``AgeRating``.

- Adds ``AgeRating.metron_name`` / ``AgeRating.metron_index`` and backfills
  them from each row's ``name`` via comicbox's ``to_metron_age_rating()``.
- Adds ``GroupAuth.age_rating_metron`` for admin-facing age restrictions.
- Renames ``SettingsBrowserFilters.age_rating`` to ``age_rating_tagged`` and
  adds the parallel ``age_rating_metron`` JSON column.
- Registers the new ``AR`` (``AGE_RATING_DEFAULT``) admin flag and seeds it
  with ``Adult`` (most-secure default).

Rebuild the ComicFTS virtual table with the new age-rating columns.

Adds ``age_rating_tagged`` (original tagged name) and ``age_rating_metron``
(normalized Metron value) as first-class FTS columns — replacing the single
``age_rating`` column from 0029. ``ComicFTS`` is unmanaged; its Django state
only tracks ``comic`` + timestamps, so the full column list is owned by
SQL. The search index will be repopulated on the next librarian sync.
"""

from comicbox.enums.maps.age_rating import to_metron_age_rating
from comicbox.enums.metroninfo import MetronAgeRatingEnum
from django.db import migrations, models

import codex.models.fields

_AR_FLAG_KEY = "AR"
_DEFAULT_RATING = MetronAgeRatingEnum.ADULT.value
_CHUNK = 500

_METRON_RATING_ORDER = (
    MetronAgeRatingEnum.EVERYONE.value,
    MetronAgeRatingEnum.TEEN.value,
    MetronAgeRatingEnum.TEEN_PLUS.value,
    MetronAgeRatingEnum.MATURE.value,
    MetronAgeRatingEnum.EXPLICIT.value,
    MetronAgeRatingEnum.ADULT.value,
)
_UNRANKED = -1
_NEW_FTS_SQL = (
    "CREATE VIRTUAL TABLE codex_comicfts USING fts5("
    "comic_id UNINDEXED, created_at UNINDEXED, updated_at UNINDEXED, "
    "publisher, imprint, series, name, collection_title, "
    "age_rating_tagged, age_rating_metron, country, language, "
    "original_format, review, scan_info, summary, tagger, characters, "
    "credits, genres, locations, roles, series_groups, stories, "
    "story_arcs, tags, teams, universes, sources"
    ")"
)


def _compute_metron_for_name(name):
    """Map an ``AgeRating.name`` to a ``(metron_name, metron_index)`` pair."""
    if not name:
        return "", _UNRANKED
    result = to_metron_age_rating(name)
    if result is None:
        return "", _UNRANKED
    metron_name = result.value
    try:
        return metron_name, _METRON_RATING_ORDER.index(metron_name)
    except ValueError:
        return metron_name, _UNRANKED


def _backfill_age_rating_metron(apps, _schema_editor) -> None:
    """Populate ``AgeRating.metron_name`` / ``metron_index`` from ``name``."""
    age_rating_model = apps.get_model("codex", "agerating")
    qs = age_rating_model.objects.only("pk", "name")
    to_update = []
    for age_rating in qs.iterator(chunk_size=_CHUNK):
        metron_name, metron_index = _compute_metron_for_name(age_rating.name)
        age_rating.metron_name = metron_name
        age_rating.metron_index = metron_index
        to_update.append(age_rating)
    if to_update:
        age_rating_model.objects.bulk_update(
            to_update, ["metron_name", "metron_index"], batch_size=_CHUNK
        )


def _seed_age_rating_default_flag(apps, _schema_editor) -> None:
    """Seed AGE_RATING_DEFAULT flag with Adult (most-secure default)."""
    admin_flag_model = apps.get_model("codex", "adminflag")
    flag, _created = admin_flag_model.objects.get_or_create(
        key=_AR_FLAG_KEY,
        defaults={"value": _DEFAULT_RATING},
    )
    if not flag.value:
        # Upgrade case: row pre-seeded by app init with value="".
        flag.value = _DEFAULT_RATING
        flag.save(update_fields=["value"])


def _noop(_apps, _schema_editor) -> None:
    """Reverse no-op (data migrations stay applied on rollback)."""


class Migration(migrations.Migration):
    """Metron-normalised age-rating data model."""

    dependencies = [
        ("codex", "0038_settings_tables"),
    ]

    operations = [
        # AgeRating: cached Metron rating + order
        migrations.AddField(
            model_name="agerating",
            name="metron_name",
            field=codex.models.fields.CleaningCharField(
                blank=True,
                db_collation="nocase",
                db_index=True,
                default="",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="agerating",
            name="metron_index",
            field=models.IntegerField(db_index=True, default=_UNRANKED),
        ),
        # GroupAuth: per-group Metron age restriction
        migrations.AddField(
            model_name="groupauth",
            name="age_rating_metron",
            field=codex.models.fields.CleaningCharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("Everyone", "Everyone"),
                    ("Teen", "Teen"),
                    ("Teen Plus", "Teen Plus"),
                    ("Mature", "Mature"),
                    ("Explicit", "Explicit"),
                    ("Adult", "Adult"),
                ],
                db_collation="nocase",
                db_index=True,
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        # SettingsBrowserFilters: rename tagged filter, add metron filter
        migrations.RenameField(
            model_name="settingsbrowserfilters",
            old_name="age_rating",
            new_name="age_rating_tagged",
        ),
        migrations.AddField(
            model_name="settingsbrowserfilters",
            name="age_rating_metron",
            field=models.JSONField(default=list),
        ),
        # AdminFlag: register the AGE_RATING_DEFAULT (``AR``) key
        migrations.AlterField(
            model_name="adminflag",
            name="key",
            field=models.CharField(
                choices=[
                    ("AR", "Age Rating Default"),
                    ("AU", "Auto Update"),
                    ("BT", "Banner Text"),
                    ("FV", "Folder View"),
                    ("IM", "Import Metadata"),
                    ("LI", "Lazy Import Metadata"),
                    ("NU", "Non Users"),
                    ("RG", "Registration"),
                    ("ST", "Send Telemetry"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS codex_comicfts;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_NEW_FTS_SQL,
            reverse_sql="DROP TABLE IF EXISTS codex_comicfts;",
        ),
        # Data migrations
        migrations.RunPython(_backfill_age_rating_metron, _noop),
        migrations.RunPython(_seed_age_rating_default_flag, _noop),
        # ComicFTS is unmanaged; its Django state tracks only (comic,
        # created_at, updated_at). The FTS columns are a SQL-level concern —
        # no state_operations are needed, only a raw DROP + CREATE.
    ]
