# Generated by Django 5.2.3 on 2025-06-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0039_alter_librarianstatus_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminflag',
            name='key',
            field=models.CharField(choices=[('AU', 'Auto Update'), ('BT', 'Banner Text'), ('FV', 'Folder View'), ('IM', 'Import Metadata'), ('LI', 'Lazy Import Metadata'), ('NU', 'Non Users'), ('RG', 'Registration'), ('ST', 'Send Telemetry')], db_index=True, max_length=2),
        ),
    ]
