"""Generated by Django 6.0.5 on 2026-05-25 02:40."""

import django.db.migrations.operations.special
from django.db import migrations, models

import codex.models.fields


def seed_defaults(apps, _schema_editor):
    """Create the singleton defaults row."""
    ComicboxTaggingDefaults = apps.get_model("codex", "ComicboxTaggingDefaults")
    ComicboxTaggingDefaults.objects.get_or_create(
        pk=1,
        defaults={
            "default_formats": ["COMIC_INFO"],
            "default_sources": ["metron", "comicvine"],
        },
    )


class Migration(migrations.Migration):
    """Migrate db."""

    dependencies = [
        ("codex", "0042_browser_table_view_and_favorites"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComicboxTaggingDefaults",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_formats", models.JSONField(default=list)),
                ("delete_original", models.BooleanField(default=False)),
                (
                    "default_match_mode",
                    models.CharField(
                        choices=[
                            ("strict", "Strict"),
                            ("normal", "Normal"),
                            ("fast", "Fast"),
                        ],
                        default="normal",
                        max_length=32,
                    ),
                ),
                (
                    "default_prompts_mode",
                    models.CharField(
                        choices=[("ask", "Ask"), ("never", "Never")],
                        default="ask",
                        max_length=32,
                    ),
                ),
                ("default_sources", models.JSONField(default=list)),
                ("prompt_timeout_seconds", models.IntegerField(default=3600)),
                (
                    "metron_user",
                    codex.models.fields.EncryptedCharField(
                        blank=True, default="", max_length=512
                    ),
                ),
                (
                    "metron_password",
                    codex.models.fields.EncryptedCharField(
                        blank=True, default="", max_length=512
                    ),
                ),
                ("metron_url", models.URLField(blank=True, default="", max_length=256)),
                (
                    "comicvine_key",
                    codex.models.fields.EncryptedCharField(
                        blank=True, default="", max_length=512
                    ),
                ),
                (
                    "comicvine_url",
                    models.URLField(blank=True, default="", max_length=256),
                ),
                (
                    "active_session_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("active_prompts", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "ComicboxTaggingDefaults",
                "abstract": False,
                "get_latest_by": "updated_at",
            },
        ),
        migrations.RunPython(
            code=seed_defaults,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="comicboxtaggingdefaults",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="librarianstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("CCC", "Create Covers"),
                    ("CFO", "Find Orphan Covers"),
                    ("CRC", "Remove Covers"),
                    ("IAT", "Aggregate Tags From Comics"),
                    ("ICC", "Create Comics"),
                    ("ICT", "Create Tags"),
                    ("ICV", "Create Custom Covers"),
                    ("IFC", "Mark Failed Failed Imports"),
                    ("IFD", "Clean Up Failed Imports"),
                    ("IFQ", "Query Failed Imports"),
                    ("IFU", "Update Failed Imports"),
                    ("IGU", "Update Timestamps For Browser Groups"),
                    ("ILT", "Link Tags"),
                    ("ILV", "Link Custom Covers"),
                    ("IMC", "Move Comics"),
                    ("IMF", "Move Folders"),
                    ("IMV", "Move Custom Covers"),
                    ("IQC", "Query Comics"),
                    ("IQL", "Query Tag Links"),
                    ("IQT", "Query Missing Tags"),
                    ("IQV", "Query Missing Custom Covers"),
                    ("IRC", "Remove Comics"),
                    ("IRF", "Remove Folders"),
                    ("IRT", "Read Tags From Comics"),
                    ("IRV", "Remove Custom Covers"),
                    ("ISC", "Create Search Index Entries"),
                    ("ISU", "Update Search Index Entries"),
                    ("IUC", "Update Comics"),
                    ("IUF", "Update Folders"),
                    ("IUT", "Update Tags"),
                    ("IUV", "Update Custom Covers"),
                    ("JAF", "Adopt Orphan Folders"),
                    ("JAS", "Cleanup Orphan Settings"),
                    ("JCT", "Cleanup Orphan Tags"),
                    ("JCU", "Update Codex Server Software"),
                    ("JDB", "Backup Database"),
                    ("JDO", "Optimize Database"),
                    ("JID", "Check Integrity Of Entire Database"),
                    ("JIF", "Check Integrtity Of Database Foreign Keys"),
                    ("JIS", "Check Integrity Of Full Text Virtual Table"),
                    ("JLV", "Check Codex Latest Version"),
                    ("JRB", "Cleanup Orphan Bookmarks"),
                    ("JRF", "Cleanup Orphan Favorites"),
                    ("JRS", "Cleanup Old Sessions"),
                    ("JRV", "Cleanup Orphan Covers"),
                    ("JSR", "Rebuild Full Text Search Virtual Table"),
                    ("OTG", "Look Up Online Tags"),
                    ("OTP", "Await Prompts Pending"),
                    ("RCR", "Restart Codex Server"),
                    ("RCS", "Stop Codex Server"),
                    ("SIO", "Optimize Search Virtual Table"),
                    ("SIR", "Clean Orphan Search Entries"),
                    ("SIX", "Clear Full Text Search Table"),
                    ("SSC", "Sync New Search Entries"),
                    ("SSU", "Sync Old Search Entries"),
                    ("TWR", "Write Comic Tags"),
                    ("WPO", "Poll Library"),
                    ("WRS", "Restart File Watcher"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
    ]
