# Generated by Django 6.0.5 on 2026-05-09 07:30
"""
Add :class:`Favorite` for per-user favorites.

Spans every browseable group (Publisher, Imprint, Series, Volume,
Folder, StoryArc) and Comic. A single table keyed by
``(user, group, target_id)`` where ``group`` is the same single-letter
code already used in browser URLs. The composite unique constraint
doubles as the lookup index for both the "favorites only" filter and
the per-row ``Exists`` annotation in table view.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the ``Favorite`` table."""

    dependencies = [
        ("codex", "0042_browser_table_view"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("p", "Publisher"),
                            ("i", "Imprint"),
                            ("s", "Series"),
                            ("v", "Volume"),
                            ("f", "Folder"),
                            ("a", "Story Arc"),
                            ("c", "Comic"),
                        ],
                        max_length=1,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
                "unique_together": {("user", "group", "target_id")},
            },
        ),
    ]
