# Generated by Django 6.0.5 on 2026-05-09 07:57
"""
Add the ``favorite`` browser filter and refresh the librarian-status choices.

``SettingsBrowserFilters.favorite`` is a plain boolean toggle —
"favorites only" — that the browser filter pipeline reads alongside
``bookmark``. Default ``False`` means existing rows opt in to "show
everything" without backfill.

The :class:`LibrarianStatus` ``status_type`` choice list grows by one
entry (``JRF`` Cleanup Orphan Favorites) added in 0043's signal/cron
phase — Django's autodetector emitted it together with this filter
field, and the merge is harmless.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add favorite filter + register the JRF librarian status."""

    dependencies = [
        ("codex", "0043_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsbrowserfilters",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="librarianstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("CCC", "Create Covers"),
                    ("CFO", "Find Orphan Covers"),
                    ("CRC", "Remove Covers"),
                    ("IAT", "Aggregate Tags From Comics"),
                    ("ICC", "Create Comics"),
                    ("ICT", "Create Tags"),
                    ("ICV", "Create Custom Covers"),
                    ("IFC", "Mark Failed Failed Imports"),
                    ("IFD", "Clean Up Failed Imports"),
                    ("IFQ", "Query Failed Imports"),
                    ("IFU", "Update Failed Imports"),
                    ("IGU", "Update Timestamps For Browser Groups"),
                    ("ILT", "Link Tags"),
                    ("ILV", "Link Custom Covers"),
                    ("IMC", "Move Comics"),
                    ("IMF", "Move Folders"),
                    ("IMV", "Move Custom Covers"),
                    ("IQC", "Query Comics"),
                    ("IQL", "Query Tag Links"),
                    ("IQT", "Query Missing Tags"),
                    ("IQV", "Query Missing Custom Covers"),
                    ("IRC", "Remove Comics"),
                    ("IRF", "Remove Folders"),
                    ("IRT", "Read Tags From Comics"),
                    ("IRV", "Remove Custom Covers"),
                    ("ISC", "Create Search Index Entries"),
                    ("ISU", "Update Search Index Entries"),
                    ("IUC", "Update Comics"),
                    ("IUF", "Update Folders"),
                    ("IUT", "Update Tags"),
                    ("IUV", "Update Custom Covers"),
                    ("JAF", "Adopt Orphan Folders"),
                    ("JAS", "Cleanup Orphan Settings"),
                    ("JCT", "Cleanup Orphan Tags"),
                    ("JCU", "Update Codex Server Software"),
                    ("JDB", "Backup Database"),
                    ("JDO", "Optimize Database"),
                    ("JID", "Check Integrity Of Entire Database"),
                    ("JIF", "Check Integrtity Of Database Foreign Keys"),
                    ("JIS", "Check Integrity Of Full Text Virtual Table"),
                    ("JLV", "Check Codex Latest Version"),
                    ("JRB", "Cleanup Orphan Bookmarks"),
                    ("JRF", "Cleanup Orphan Favorites"),
                    ("JRS", "Cleanup Old Sessions"),
                    ("JRV", "Cleanup Orphan Covers"),
                    ("JSR", "Rebuild Full Text Search Virtual Table"),
                    ("RCR", "Restart Codex Server"),
                    ("RCS", "Stop Codex Server"),
                    ("SIO", "Optimize Search Virtual Table"),
                    ("SIR", "Clean Orphan Search Entries"),
                    ("SIX", "Clear Full Text Search Table"),
                    ("SSC", "Sync New Search Entries"),
                    ("SSU", "Sync Old Search Entries"),
                    ("WPO", "Poll Library"),
                    ("WRS", "Restart File Watcher"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
    ]
