# Generated by Django 6.0.5 on 2026-05-09 08:09
"""
Refresh ``SettingsBrowser.order_by`` choices to include ``favorite``.

Phase 5 of the favorites feature adds ``favorite`` as a sortable
table-view column. The order-by enum needs the new key so the choice
validator stops rejecting requests with ``order_by=favorite``. The
``favorite`` annotation itself is wired in
``BrowserView._add_table_view_favorite_annotation`` and added to
every browseable queryset (group + comic) before ``add_order_by``.

Pure choice-metadata edit on an existing CharField column; no
``ALTER TABLE`` runs.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Register the ``favorite`` sort key."""

    dependencies = [
        ("codex", "0044_settingsbrowserfilters_favorite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsbrowser",
            name="order_by",
            field=models.CharField(
                choices=[
                    ("created_at", "Added Time"),
                    ("age_rating", "Age Rating"),
                    ("characters", "Characters"),
                    ("child_count", "Child Count"),
                    ("country", "Country"),
                    ("credits", "Credits"),
                    ("critical_rating", "Critical Rating"),
                    ("day", "Day"),
                    ("favorite", "Favorite"),
                    ("filename", "Filename"),
                    ("size", "File Size"),
                    ("file_type", "File Type"),
                    ("original_format", "Format"),
                    ("genres", "Genres"),
                    ("identifiers", "Identifiers"),
                    ("imprint_name", "Imprint"),
                    ("issue", "Issue"),
                    ("language", "Language"),
                    ("bookmark_updated_at", "Last Read"),
                    ("locations", "Locations"),
                    ("main_character", "Main Character"),
                    ("main_team", "Main Team"),
                    ("metadata_mtime", "Metadata Updated"),
                    ("month", "Month"),
                    ("monochrome", "Monochrome"),
                    ("sort_name", "Name"),
                    ("page_count", "Page Count"),
                    ("publisher_name", "Publisher"),
                    ("date", "Publish Date"),
                    ("reading_direction", "Reading Direction"),
                    ("scan_info", "Scan Info"),
                    ("search_score", "Search Score"),
                    ("series_name", "Series"),
                    ("series_groups", "Series Groups"),
                    ("stories", "Stories"),
                    ("story_arc_number", "Story Arc Number"),
                    ("story_arcs", "Story Arcs"),
                    ("tags", "Tags"),
                    ("tagger", "Tagger"),
                    ("teams", "Teams"),
                    ("universes", "Universes"),
                    ("updated_at", "Updated Time"),
                    ("volume_name", "Volume"),
                    ("year", "Year"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
