"""Generated by Django 6.0.6 on 2026-06-23 03:01."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add read_only flag to Library."""

    dependencies = [
        ("codex", "0044_alter_librarianstatus_status_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="read_only",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
