"""Generated by Django 6.0.6 on 2026-06-30 09:10."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add rename_files flag to ComicboxTaggingDefaults."""

    dependencies = [
        ("codex", "0045_library_read_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="comicboxtaggingdefaults",
            name="rename_files",
            field=models.BooleanField(default=False),
        ),
    ]
