# Generated by Django 6.0.7 on 2026-07-22 04:15
"""
comicbox 4.4.0: community_rating replaces critical_rating; alternative issue.

The RenameFields carry the column values (critical_rating's data came
from ComicInfo CommunityRating / CBI rating — community semantics all
along). The RunPython remaps the *contents* of user settings that
reference the old key: SettingsBrowser.order_by values and
SettingsBrowser.table_columns JSON dict keys — RenameField never touches
JSON payloads or enum values (the 0043 table_columns lesson).
"""

from django.db import migrations, models

import codex.models.fields

_OLD_KEY = "critical_rating"
_NEW_KEY = "community_rating"


def _remap_browser_settings(apps, _schema_editor):
    _remap(apps, _OLD_KEY, _NEW_KEY)


def _unremap_browser_settings(apps, _schema_editor):
    _remap(apps, _NEW_KEY, _OLD_KEY)


def _remap(apps, old, new):
    settings_browser = apps.get_model("codex", "SettingsBrowser")
    settings_browser.objects.filter(order_by=old).update(order_by=new)
    # JSON dict keys need a python pass; .filter(table_columns__has_key=...)
    # is unsupported on SQLite JSONField, so scan and rewrite sparsely.
    rows = []
    for row in settings_browser.objects.exclude(table_columns={}).only(
        "pk", "table_columns"
    ):
        columns = row.table_columns
        if isinstance(columns, dict) and old in columns:
            columns[new] = columns.pop(old)
            rows.append(row)
    if rows:
        settings_browser.objects.bulk_update(rows, ["table_columns"])


class Migration(migrations.Migration):
    """community_rating replaces critical_rating; alternative issue columns."""

    dependencies = [
        ("codex", "0047_oidc_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comic",
            old_name="critical_rating",
            new_name="community_rating",
        ),
        migrations.RenameField(
            model_name="settingsbrowserfilters",
            old_name="critical_rating",
            new_name="community_rating",
        ),
        migrations.AddField(
            model_name="comic",
            name="alternative_issue_number",
            field=codex.models.fields.CoercingDecimalField(
                decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="alternative_issue_suffix",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", default="", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="community_rating_count",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.RunPython(_remap_browser_settings, _unremap_browser_settings),
        migrations.AlterField(
            model_name="settingsbrowser",
            name="order_by",
            field=models.CharField(
                choices=[
                    ("created_at", "Added Time"),
                    ("age_rating", "Age Rating"),
                    ("characters", "Characters"),
                    ("child_count", "Child Count"),
                    ("community_rating", "Community Rating"),
                    ("country", "Country"),
                    ("credits", "Credits"),
                    ("day", "Day"),
                    ("favorite", "Favorite"),
                    ("filename", "Filename"),
                    ("size", "File Size"),
                    ("file_type", "File Type"),
                    ("original_format", "Format"),
                    ("genres", "Genres"),
                    ("identifiers", "Identifiers"),
                    ("imprint_name", "Imprint"),
                    ("issue", "Issue"),
                    ("language", "Language"),
                    ("bookmark_updated_at", "Last Read"),
                    ("locations", "Locations"),
                    ("main_character", "Main Character"),
                    ("main_team", "Main Team"),
                    ("metadata_mtime", "Tags Updated"),
                    ("month", "Month"),
                    ("monochrome", "Monochrome"),
                    ("sort_name", "Name"),
                    ("page_count", "Page Count"),
                    ("publisher_name", "Publisher"),
                    ("date", "Publish Date"),
                    ("reading_direction", "Reading Direction"),
                    ("scan_info", "Scan Info"),
                    ("search_score", "Search Score"),
                    ("series_name", "Series"),
                    ("series_groups", "Series Groups"),
                    ("stories", "Stories"),
                    ("story_arc_number", "Story Arc Number"),
                    ("story_arcs", "Story Arcs"),
                    ("tags", "Tags"),
                    ("tagger", "Tagger"),
                    ("teams", "Teams"),
                    ("universes", "Universes"),
                    ("updated_at", "Updated Time"),
                    ("volume_name", "Volume"),
                    ("year", "Year"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
