# Generated by Django 6.0.7 on 2026-07-26 05:53
"""
comicbox 4.6.0: reprints (alternate & localized series names).

comicbox 4.6.0 emits a ``reprints`` list from MetronInfo
``Series/AlternativeNames`` + ``Reprints`` and from Metron / ComicVine
online tagging. Codex stores them in a denormalized :class:`Reprint`
table rather than reusing Series/Volume — those are browse collections
and alternate names would surface as phantom browser rows.

``Reprint`` rows carry an ``Identifier``, so ``IdentifierType`` gains
its long-reserved ``reprint`` member. Reprints are also a browser order
key. Both are choices-only churn on existing columns, hence the two
``AlterField`` operations below.

The FTS5 rebuild adds the ``alternate_series`` column. ``ComicFTS`` is
unmanaged, so makemigrations never sees it — the column list lives in
SQL and has to be dropped and recreated by hand, exactly as 0039 did
for the age-rating columns. The table comes back empty; the librarian's
regular ``SearchIndexSyncTask`` repopulates it.
"""

import django.db.models.deletion
from django.db import migrations, models

import codex.models.fields

# 0039's column list plus ``alternate_series``.
_NEW_FTS_SQL = (
    "CREATE VIRTUAL TABLE codex_comicfts USING fts5("
    "comic_id UNINDEXED, created_at UNINDEXED, updated_at UNINDEXED, "
    "publisher, imprint, series, name, collection_title, "
    "age_rating_tagged, age_rating_metron, country, language, "
    "original_format, review, scan_info, summary, tagger, "
    "alternate_series, characters, "
    "credits, genres, locations, roles, series_groups, stories, "
    "story_arcs, tags, teams, universes, sources"
    ")"
)


class Migration(migrations.Migration):
    """Reprint model, comic m2m, filter column, and FTS alternate_series."""

    dependencies = [
        ("codex", "0048_community_rating_alternative_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsbrowserfilters",
            name="reprints",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("storyarc", "Arc"),
                    ("character", "Character"),
                    ("genre", "Genre"),
                    ("imprint", "Imprint"),
                    ("comic", "Issue"),
                    ("location", "Location"),
                    ("publisher", "Publisher"),
                    ("reprint", "Reprint"),
                    ("series", "Series"),
                    ("story", "Story"),
                    ("tag", "Tag"),
                    ("team", "Team"),
                    ("universe", "Universe"),
                    ("creditrole", "Role"),
                    ("creditperson", "Creator"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Reprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series_name",
                    codex.models.fields.CleaningCharField(
                        db_index=True, max_length=128
                    ),
                ),
                (
                    "volume_number",
                    codex.models.fields.CoercingPositiveSmallIntegerField(
                        default=None, null=True
                    ),
                ),
                (
                    "issue",
                    codex.models.fields.CleaningCharField(default="", max_length=32),
                ),
                (
                    "language",
                    codex.models.fields.CleaningCharField(default="", max_length=32),
                ),
                (
                    "identifier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="codex.identifier",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
                "unique_together": {
                    ("series_name", "volume_number", "issue", "language")
                },
            },
        ),
        migrations.AddField(
            model_name="comic",
            name="reprints",
            field=models.ManyToManyField(to="codex.reprint"),
        ),
        migrations.AlterField(
            model_name="settingsbrowser",
            name="order_by",
            field=models.CharField(
                choices=[
                    ("created_at", "Added Time"),
                    ("age_rating", "Age Rating"),
                    ("reprints", "Alternate Series"),
                    ("characters", "Characters"),
                    ("child_count", "Child Count"),
                    ("community_rating", "Community Rating"),
                    ("country", "Country"),
                    ("credits", "Credits"),
                    ("day", "Day"),
                    ("favorite", "Favorite"),
                    ("filename", "Filename"),
                    ("size", "File Size"),
                    ("file_type", "File Type"),
                    ("original_format", "Format"),
                    ("genres", "Genres"),
                    ("identifiers", "Identifiers"),
                    ("imprint_name", "Imprint"),
                    ("issue", "Issue"),
                    ("language", "Language"),
                    ("bookmark_updated_at", "Last Read"),
                    ("locations", "Locations"),
                    ("main_character", "Main Character"),
                    ("main_team", "Main Team"),
                    ("metadata_mtime", "Tags Updated"),
                    ("month", "Month"),
                    ("monochrome", "Monochrome"),
                    ("sort_name", "Name"),
                    ("page_count", "Page Count"),
                    ("publisher_name", "Publisher"),
                    ("date", "Publish Date"),
                    ("reading_direction", "Reading Direction"),
                    ("scan_info", "Scan Info"),
                    ("search_score", "Search Score"),
                    ("series_name", "Series"),
                    ("series_groups", "Series Groups"),
                    ("stories", "Stories"),
                    ("story_arc_number", "Story Arc Number"),
                    ("story_arcs", "Story Arcs"),
                    ("tags", "Tags"),
                    ("tagger", "Tagger"),
                    ("teams", "Teams"),
                    ("universes", "Universes"),
                    ("updated_at", "Updated Time"),
                    ("volume_name", "Volume"),
                    ("year", "Year"),
                ],
                default="",
                max_length=32,
            ),
        ),
        # ComicFTS is unmanaged; its Django state tracks only (comic,
        # created_at, updated_at). The FTS columns are a SQL-level concern —
        # no state_operations are needed, only a raw DROP + CREATE.
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS codex_comicfts;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_NEW_FTS_SQL,
            reverse_sql="DROP TABLE IF EXISTS codex_comicfts;",
        ),
    ]
