"""Generated by Django 6.0.6 on 2026-07-28 12:00."""

from django.db import migrations

import codex.models.fields


class Migration(migrations.Migration):
    """Add metron_key API token to ComicboxTaggingDefaults."""

    dependencies = [
        ("codex", "0049_reprints"),
    ]

    operations = [
        migrations.AddField(
            model_name="comicboxtaggingdefaults",
            name="metron_key",
            field=codex.models.fields.EncryptedCharField(
                blank=True, default="", max_length=512
            ),
        ),
    ]
