"""Generated by Django 6.0.7 on 2026-07-29 06:10."""

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove the custom Metron & Comic Vine URL overrides.

    The Metron override was always a no-op: mokkari hardcodes its API
    endpoint, and comicbox's metron source warns that the url is ignored.
    The Comic Vine override worked but serves no purpose for this app.
    comicbox still defines the fields on its credentials dataclass; codex
    just stops passing them.
    """

    dependencies = [
        ("codex", "0050_comicboxtaggingdefaults_metron_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comicboxtaggingdefaults",
            name="comicvine_url",
        ),
        migrations.RemoveField(
            model_name="comicboxtaggingdefaults",
            name="metron_url",
        ),
    ]
