"""Generated by Django 6.0.7 on 2026-08-03 12:00."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Restore the custom Comic Vine URL override removed by 0051.

    Only the Comic Vine half comes back. comicbox passes the url through to
    simyan's ``base_url``, so pointing tagging at a Comic Vine proxy or mirror
    works. Metron's twin stays gone: mokkari hardcodes its API endpoint and
    comicbox warns that the url is ignored.

    0051 dropped the column outright, so any URL saved before it is
    unrecoverable — admins re-enter it.
    """

    dependencies = [
        ("codex", "0051_remove_comicboxtaggingdefaults_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="comicboxtaggingdefaults",
            name="comicvine_url",
            field=models.URLField(blank=True, default="", max_length=256),
        ),
    ]
