"""
The v2.3.0 schema: comicbox 5's fields, reprint sorting, sort memory.

Everything here ships in one release, so a database migrates through it
once rather than walking a chain of steps no installed version ever
stopped at.

**Comicbox 5.** ``manga`` is no longer entangled with reading direction:
ComicInfo compounds the two in one ``YesAndRightToLeft`` value, and
comicbox now reports each on its own, so there is a column for each.
``manga_volume`` is MetronInfo's MangaVolume, kept as the file wrote it.
``urls`` holds the web links the file itself carries, which is where they
live now that an identifier is only a key; the links codex derives from
those keys are built on demand and are not these.

``Credit.primary`` marks the book's primary holder of a role. The flag
belongs to the person-and-role pairing rather than the person, which is
the point of comicbox moving it onto each role: the primary writer is
not thereby also the primary inker. Credit rows are shared between
comics, so a pairing that is primary in one book and not in another must
be two rows, and the flag joins the unique key to allow that.

``Reprint.alternative_name`` records that a row came from the series'
other names rather than from a list of reprints. Both name another
edition of the same book, so they share the table and the key; the flag
only decides which comicbox list a write puts the row back into.

The ``volume`` identifier type is the sixteenth and last: comicbox names
sixteen and codex named fifteen, so a comicbox ``volume`` id had no
codex table to point at.

``default_effort`` is the API budget an online scan spends per comic.
Comicbox 5 bounds Comic Vine's per-candidate fan-out, and this is how an
admin widens or narrows it. It defaults to unset rather than to a named
budget, because naming one tells comicbox to leave it alone: only while
nobody has named a budget is comicbox free to spend less on a run large
enough to otherwise stretch into hours of Comic Vine rate limiting.

None of those columns is backfilled. A comic keeps its defaults until it
is next read, which is deliberate: they can only be filled from the file,
so filling them means re-reading every archive in the library. That is an
admin's call, and the release notes say how to make it.

**Reprint sorting.** The Reprints order_by key sorts comics by their
issue within a reprint series. ``issue`` is a string, so sorting it
directly puts "#10" before "#2"; the derived columns mirror
``Comic.issue_number`` / ``issue_suffix`` and are backfilled here,
because they are derived from a column the database already holds.

**Sort memory.** ``SettingsBrowser.collection_order_memory`` remembers
the sort each top collection was last browsed with. Switching top
collections used to drag one global sort along with it, so sorting issues
by added time and then looking at publishers left the publisher list in
added-time order too. The new map is empty for every existing row, which
reads as "no collection has been customized yet" and keeps the old
carry-the-sort-over behavior until someone changes a sort.

Generated by Django 6.1 on 2026-08-30, extended 2026-09-08.
"""

from django.db import migrations, models

import codex.models.fields
from codex.models.util import parse_issue_parts

_BATCH_SIZE = 1000


def _backfill_reprint_issue_parts(apps, _schema_editor) -> None:
    """Derive issue_number & issue_suffix for existing reprints."""
    reprint_model = apps.get_model("codex", "Reprint")
    # Historical models don't carry ``presave``, so parse here.
    updates = []
    for reprint in reprint_model.objects.exclude(issue="").iterator():
        issue_number, issue_suffix = parse_issue_parts(reprint.issue)
        if issue_number is None and not issue_suffix:
            continue
        reprint.issue_number = issue_number
        reprint.issue_suffix = issue_suffix
        updates.append(reprint)

    for start in range(0, len(updates), _BATCH_SIZE):
        reprint_model.objects.bulk_update(
            updates[start : start + _BATCH_SIZE], ["issue_number", "issue_suffix"]
        )


class Migration(migrations.Migration):
    """Add the v2.3.0 columns and backfill the reprint issue parts."""

    dependencies = [
        ("codex", "0052_comicboxtaggingdefaults_comicvine_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="reprint",
            name="issue_number",
            field=codex.models.fields.CoercingDecimalField(
                decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="reprint",
            name="issue_suffix",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", default="", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="settingsbrowser",
            name="order_by",
            field=models.CharField(
                choices=[
                    ("created_at", "Added Time"),
                    ("age_rating", "Age Rating"),
                    ("characters", "Characters"),
                    ("child_count", "Child Count"),
                    ("community_rating", "Community Rating"),
                    ("country", "Country"),
                    ("credits", "Credits"),
                    ("day", "Day"),
                    ("favorite", "Favorite"),
                    ("filename", "Filename"),
                    ("size", "File Size"),
                    ("file_type", "File Type"),
                    ("original_format", "Format"),
                    ("genres", "Genres"),
                    ("identifiers", "Identifiers"),
                    ("imprint_name", "Imprint"),
                    ("issue", "Issue"),
                    ("language", "Language"),
                    ("bookmark_updated_at", "Last Read"),
                    ("locations", "Locations"),
                    ("main_character", "Main Character"),
                    ("main_team", "Main Team"),
                    ("metadata_mtime", "Tags Updated"),
                    ("month", "Month"),
                    ("monochrome", "Monochrome"),
                    ("sort_name", "Name"),
                    ("page_count", "Page Count"),
                    ("publisher_name", "Publisher"),
                    ("date", "Publish Date"),
                    ("reading_direction", "Reading Direction"),
                    ("reprints", "Reprints"),
                    ("scan_info", "Scan Info"),
                    ("search_score", "Search Score"),
                    ("series_name", "Series"),
                    ("series_groups", "Series Groups"),
                    ("stories", "Stories"),
                    ("story_arc_number", "Story Arc Number"),
                    ("story_arcs", "Story Arcs"),
                    ("tags", "Tags"),
                    ("tagger", "Tagger"),
                    ("teams", "Teams"),
                    ("universes", "Universes"),
                    ("updated_at", "Updated Time"),
                    ("volume_name", "Volume"),
                    ("year", "Year"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="settingsbrowser",
            name="collection_order_memory",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name="credit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="comic",
            name="manga",
            field=codex.models.fields.CleaningCharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                db_collation="nocase",
                default="Unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="manga_volume",
            field=codex.models.fields.CleaningCharField(
                blank=True, db_collation="nocase", default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="urls",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="comicboxtaggingdefaults",
            name="default_effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Auto"),
                    ("minimal", "Minimal"),
                    ("balanced", "Balanced"),
                    ("thorough", "Thorough"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reprint",
            name="alternative_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="identifier",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("storyarc", "Arc"),
                    ("character", "Character"),
                    ("genre", "Genre"),
                    ("imprint", "Imprint"),
                    ("comic", "Issue"),
                    ("location", "Location"),
                    ("publisher", "Publisher"),
                    ("reprint", "Reprint"),
                    ("series", "Series"),
                    ("story", "Story"),
                    ("tag", "Tag"),
                    ("team", "Team"),
                    ("universe", "Universe"),
                    ("volume", "Volume"),
                    ("creditrole", "Role"),
                    ("creditperson", "Creator"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="credit",
            unique_together={("person", "role", "primary")},
        ),
        migrations.RunPython(
            _backfill_reprint_issue_parts,
            migrations.RunPython.noop,
        ),
    ]
