"""
Split Reprint.issue into sortable columns & remember sorts per collection.

The ``alternate_number`` order_by key sorts comics by their
ComicInfo ``AlternateNumber`` within an alternate series. ``issue``
is a string, so sorting it directly puts "#10" before "#2"; these
derived columns mirror ``Comic.issue_number`` / ``issue_suffix``.

``SettingsBrowser.collection_order_memory`` remembers the sort each top
collection was last browsed with. Switching top collections used to drag one
global sort along with it, so sorting issues by added time and then looking at
publishers left the publisher list in added-time order too. The new map is
empty for every existing row, which reads as "no collection has been
customized yet" and keeps the current carry-the-sort-over behavior until
someone changes a sort. Nothing to backfill.

Generated by Django 6.1 on 2026-08-30 06:03.
"""

from django.db import migrations, models

import codex.models.fields
from codex.models.util import parse_issue_parts

_BATCH_SIZE = 1000


def _backfill_reprint_issue_parts(apps, _schema_editor) -> None:
    """Derive issue_number & issue_suffix for existing reprints."""
    reprint_model = apps.get_model("codex", "Reprint")
    # Historical models don't carry ``presave``, so parse here.
    updates = []
    for reprint in reprint_model.objects.exclude(issue="").iterator():
        issue_number, issue_suffix = parse_issue_parts(reprint.issue)
        if issue_number is None and not issue_suffix:
            continue
        reprint.issue_number = issue_number
        reprint.issue_suffix = issue_suffix
        updates.append(reprint)

    for start in range(0, len(updates), _BATCH_SIZE):
        reprint_model.objects.bulk_update(
            updates[start : start + _BATCH_SIZE], ["issue_number", "issue_suffix"]
        )


class Migration(migrations.Migration):
    """Add Reprint issue sort columns, backfill them & add the sort memory."""

    dependencies = [
        ("codex", "0052_comicboxtaggingdefaults_comicvine_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="reprint",
            name="issue_number",
            field=codex.models.fields.CoercingDecimalField(
                decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="reprint",
            name="issue_suffix",
            field=codex.models.fields.CleaningCharField(
                db_collation="nocase", default="", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="settingsbrowser",
            name="order_by",
            field=models.CharField(
                choices=[
                    ("created_at", "Added Time"),
                    ("age_rating", "Age Rating"),
                    ("alternate_number", "Alternate Number"),
                    ("reprints", "Alternate Series"),
                    ("characters", "Characters"),
                    ("child_count", "Child Count"),
                    ("community_rating", "Community Rating"),
                    ("country", "Country"),
                    ("credits", "Credits"),
                    ("day", "Day"),
                    ("favorite", "Favorite"),
                    ("filename", "Filename"),
                    ("size", "File Size"),
                    ("file_type", "File Type"),
                    ("original_format", "Format"),
                    ("genres", "Genres"),
                    ("identifiers", "Identifiers"),
                    ("imprint_name", "Imprint"),
                    ("issue", "Issue"),
                    ("language", "Language"),
                    ("bookmark_updated_at", "Last Read"),
                    ("locations", "Locations"),
                    ("main_character", "Main Character"),
                    ("main_team", "Main Team"),
                    ("metadata_mtime", "Tags Updated"),
                    ("month", "Month"),
                    ("monochrome", "Monochrome"),
                    ("sort_name", "Name"),
                    ("page_count", "Page Count"),
                    ("publisher_name", "Publisher"),
                    ("date", "Publish Date"),
                    ("reading_direction", "Reading Direction"),
                    ("scan_info", "Scan Info"),
                    ("search_score", "Search Score"),
                    ("series_name", "Series"),
                    ("series_groups", "Series Groups"),
                    ("stories", "Stories"),
                    ("story_arc_number", "Story Arc Number"),
                    ("story_arcs", "Story Arcs"),
                    ("tags", "Tags"),
                    ("tagger", "Tagger"),
                    ("teams", "Teams"),
                    ("universes", "Universes"),
                    ("updated_at", "Updated Time"),
                    ("volume_name", "Volume"),
                    ("year", "Year"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="settingsbrowser",
            name="collection_order_memory",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(
            _backfill_reprint_issue_parts,
            migrations.RunPython.noop,
        ),
    ]
