"""Generated by Django 6.0.7 on 2026-08-30 12:00."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Remember the sort each top collection was last browsed with.

    Switching top collections used to drag one global sort along with it, so
    sorting issues by added time and then looking at publishers left the
    publisher list in added-time order too.

    The new map is empty for every existing row, which reads as "no collection
    has been customized yet" and keeps the current carry-the-sort-over
    behavior until someone changes a sort. Nothing to backfill.
    """

    dependencies = [
        ("codex", "0053_reprint_issue_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsbrowser",
            name="collection_order_memory",
            field=models.JSONField(default=dict),
        ),
    ]
