"""
One bookmark per owner per comic, enforced by the database.

``Bookmark.unique_together = (user, session, comic)`` never enforced
anything. Both owner columns are nullable, and SQL treats NULLs in a
unique index as distinct, so ``(user=1, session=NULL, comic=5)`` could be
stored any number of times. The two-pass writer avoids minting duplicates
by selecting first and inserting only what it did not find, but nothing
serialized those two steps: a queued page turn and a synchronous
mark-read for the same comic both find nothing and both insert.

A duplicate is not cosmetic. The browser sums ``page`` and ``finished``
over the rows, so a comic can report more finished children than it has;
the reader takes whichever row it reads last; and OPDS progression and
the settings restore both fetch a single row and raise
``MultipleObjectsReturned``, which surfaces as a 500.

Two partial unique constraints say what was meant, each conditioned on
its own owner being present so the NULLs are out of the picture. Rows
that already violate them are merged first: the most recently updated row
of a group survives and takes the group's progress with it —
``finished`` if any row was finished, and a page if the survivor has
none. Rows owned by neither a user nor a session are deleted; they are
unreachable by every query in the app, and the nightly cleanup collects
any that appear later.

SQLite rolls back DDL, and ``Migration.atomic`` is on by default, so the
merge and the constraints land together or not at all. A conditional
``UniqueConstraint`` is a ``CREATE UNIQUE INDEX … WHERE``, and dropping
``unique_together`` is a ``DROP INDEX``: no table is rebuilt, so this
stays cheap on a large library.

Generated by Django 6.1 on 2026-09-20.
"""

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, F

# Chunk the loser deletes: a pk list becomes one bound parameter per pk.
_BATCH_SIZE = 900
# The most recently updated row wins. In the session pass a row that also
# has a user outranks an anonymous one, so a signed-in reader's row is
# never the one dropped.
_ORDER = {
    "user": ("-updated_at", "-pk"),
    "session": (F("user_id").desc(nulls_last=True), "-updated_at", "-pk"),
}


def _merge_into_winner(rows) -> list[int]:
    """Fold a duplicate group into its first row; return the losers' pks."""
    winner = rows[0]
    finished = any(row.finished for row in rows)
    page = winner.page
    if page is None:
        pages = [row.page for row in rows if row.page is not None]
        page = max(pages) if pages else None
    if finished != winner.finished or page != winner.page:
        winner.finished = finished
        winner.page = page
        winner.save(update_fields=("finished", "page"))
    return [row.pk for row in rows[1:]]


def _dedupe_owner(bookmark_model, owner: str) -> int:
    """Collapse every group of rows one of the new constraints would reject."""
    owner_id = f"{owner}_id"
    groups = (
        bookmark_model.objects.filter(**{f"{owner_id}__isnull": False})
        .values(owner_id, "comic_id")
        .annotate(count=Count("pk"))
        .filter(count__gt=1)
        .order_by()
    )
    loser_pks: list[int] = []
    for group in groups:
        rows = list(
            bookmark_model.objects.filter(
                **{owner_id: group[owner_id], "comic_id": group["comic_id"]}
            ).order_by(*_ORDER[owner])
        )
        loser_pks += _merge_into_winner(rows)
    for start in range(0, len(loser_pks), _BATCH_SIZE):
        bookmark_model.objects.filter(
            pk__in=loser_pks[start : start + _BATCH_SIZE]
        ).delete()
    return len(loser_pks)


def dedupe_bookmarks(apps, _schema_editor) -> None:
    """Make the table satisfy the constraints that follow."""
    bookmark_model = apps.get_model("codex", "Bookmark")
    # The user pass runs first: a row with both owners is bound by both
    # constraints, and merging it as a user row keeps that reader's
    # progress on the row they can actually see.
    merged = {owner: _dedupe_owner(bookmark_model, owner) for owner in _ORDER}
    ownerless, _ = bookmark_model.objects.filter(
        user_id__isnull=True, session_id__isnull=True
    ).delete()
    if not (any(merged.values()) or ownerless):
        return
    print(f"\nBookmarks: merged {merged['user']} duplicate user rows.")
    print(f"Bookmarks: merged {merged['session']} duplicate session rows.")
    print(f"Bookmarks: deleted {ownerless} rows that belonged to nobody.")


class Migration(migrations.Migration):
    """Merge duplicate bookmarks, then forbid them."""

    dependencies = [
        ("codex", "0053_comicbox_5_reprints_and_sort_memory"),
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            dedupe_bookmarks,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "comic"),
                name="unique_bookmark_user_comic",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", False)),
                fields=("session", "comic"),
                name="unique_bookmark_session_comic",
            ),
        ),
    ]
