"""
Add the volume identifier type.

Comicbox names sixteen identifier types and codex named fifteen: a
comicbox ``volume`` id had no codex table to point at. Comicbox 5's
identifiers state their type when it isn't the one their position
implies, so a comic can now carry a volume id among its own, and codex
translates between the two vocabularies by matching them member for
member. This is the member that was missing.

Choices only. No column changes, and nothing to backfill: no existing
row can hold a value that wasn't a choice before.

Generated by Django 6.1.1 on 2026-09-08 05:57.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the volume identifier type."""

    dependencies = [
        ("codex", "0053_reprint_issue_number_and_collection_order_memory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("storyarc", "Arc"),
                    ("character", "Character"),
                    ("genre", "Genre"),
                    ("imprint", "Imprint"),
                    ("comic", "Issue"),
                    ("location", "Location"),
                    ("publisher", "Publisher"),
                    ("reprint", "Reprint"),
                    ("series", "Series"),
                    ("story", "Story"),
                    ("tag", "Tag"),
                    ("team", "Team"),
                    ("universe", "Universe"),
                    ("volume", "Volume"),
                    ("creditrole", "Role"),
                    ("creditperson", "Creator"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
