"""
Store the facts comicbox 5 separates out.

``manga`` is no longer entangled with reading direction: ComicInfo
compounds the two in one ``YesAndRightToLeft`` value, and comicbox now
reports each on its own, so codex has a column for each. ``manga_volume``
is MetronInfo's MangaVolume, kept as the file wrote it. ``urls`` holds
the web links the file itself carries, which is where they live now that
an identifier is only a key; the links codex derives from those keys are
built on demand and are not these.

``Credit.primary`` marks the book's primary holder of a role. The flag
belongs to the person-and-role pairing rather than the person, which is
the point of comicbox moving it onto each role: the primary writer is
not thereby also the primary inker. Credit rows are shared between
comics, so a pairing that is primary in one book and not in another must
be two rows, and the flag joins the unique key to allow that.

``Reprint.alternative_name`` records that a row came from the series'
other names rather than from a list of reprints. Both name another
edition of the same book, so they share the table and the key; the flag
only decides which comicbox list a write puts the row back into.

``default_effort`` is the API budget an online scan spends per comic.
Comicbox 5 bounds Comic Vine's per-candidate fan-out by default, and
this is how an admin asks for the old unbounded search back.

Every new column defaults, so nothing is backfilled here. Existing rows
carry those defaults until the comic is re-read, which migration 0056
arranges.

Generated by Django 6.1.1 on 2026-09-08.
"""

from django.db import migrations, models

import codex.models.fields


class Migration(migrations.Migration):
    """Add the comicbox 5 fields and the online effort setting."""

    dependencies = [
        ("codex", "0054_alter_identifier_id_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="credit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="comic",
            name="manga",
            field=codex.models.fields.CleaningCharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                db_collation="nocase",
                default="Unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="manga_volume",
            field=codex.models.fields.CleaningCharField(
                blank=True, db_collation="nocase", default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="urls",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="comicboxtaggingdefaults",
            name="default_effort",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimal"),
                    ("balanced", "Balanced"),
                    ("thorough", "Thorough"),
                ],
                default="balanced",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reprint",
            name="alternative_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="credit",
            unique_together={("person", "role", "primary")},
        ),
    ]
