"""
Re-read every comic once, under comicbox 5.

Comicbox 5 changes what existing files mean, without changing the files.
Age ratings collapse to MetronInfo's seven names, so a comic tagged
``Everyone 10+`` now reads as ``Everyone``. Credit roles canonicalize,
so CoMet's ``colorist`` becomes ``Colorist`` and ComicInfo's
``CoverArtist`` becomes ``Cover``. ComicInfo's AlternateSeries reads as a
story arc rather than as a reprint. A ComicInfo ``Manga`` of
``YesAndRightToLeft`` now also sets a reading direction. A stated title
is kept as written instead of being rebuilt from the story list.

Codex re-reads a comic only when its file changed, so without this every
one of those would stay as comicbox 4 read it, indefinitely, and a
library would hold both readings at once: the old one everywhere, the new
one on whatever happened to be re-tagged. Its browser facets would list
``Everyone`` beside ``Everyone 10+`` and ``Cover`` beside ``CoverArtist``
as though they were different things.

Nulling the stored stat is what asks for the re-read. The poller reads a
missing stat as "stat the file and call it modified", and the importer's
prefilter skips a comic only on a matching stored stat or an unadvanced
metadata mtime, so with both cleared every comic is read again. Nulling
``Library.last_poll`` brings the first pass forward to the next loop
after startup rather than waiting out ``poll_every``.

What this does not touch:

- ``poll``. A library set to manual polling stays manual; its comics are
  re-read whenever its admin next polls it.
- ``metadata_imported_at``. It marks that a comic has been through a
  metadata import at all, and drives the "not imported" hint. Clearing it
  would blank that hint across the whole library for the length of the
  re-read, which would read as data loss rather than as work in progress.

Resumable by construction: a comic gets its stat back only once it has
been imported, so an interrupted run leaves the rest still asking.

Generated by hand on 2026-09-08.
"""

from django.db import migrations


def _request_reread(apps, _schema_editor) -> None:
    """Ask the poller for every comic, and for the first pass to be soon."""
    comic_model = apps.get_model("codex", "Comic")
    library_model = apps.get_model("codex", "Library")
    comic_model.objects.update(stat=None, metadata_mtime=None)
    library_model.objects.update(last_poll=None)


def _noop(_apps, _schema_editor) -> None:
    """Nothing to undo: a re-read leaves no trace to reverse."""


class Migration(migrations.Migration):
    """Ask for one full re-read under comicbox 5's reading of the files."""

    dependencies = [
        ("codex", "0055_comicbox_5_fields"),
    ]

    operations = [
        migrations.RunPython(_request_reread, _noop),
    ]
