.: 1754090235.952218
config:
  bigger: false
  convert_to:
    - WEBP
  formats:
    - GIF
    - JPEG
    - PNG
    - SVG
    - WEBP
  ignore: []
  keep_metadata: true
  near_lossless: false
  recurse: true
  symlinks: true
treestamps_config:
  ignore: !!set {}
  symlinks: true
