name: nginx-codex
services:
  nginx:
    image: ajslater/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:9811"
    volumes:
      - /Users/aj/Code/codex/nginx/http.d/codex:/etc/nginx/http.d/codex:ro
