services:
  nginx:
    image: ajslater/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:9811"
    volumes:
      - /Users/aj/Code/codex/nginx/config/conf.d:/etc/nginx/conf.d:ro
