"""
Django settings for codex project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from os import cpu_count, environ
from pathlib import Path
from types import MappingProxyType

from comicbox.config import get_config
from comicbox.config.frozenattrdict import FrozenAttrDict
from comicbox.schemas.comicbox.yaml import ComicboxYamlSubSchema
from django.utils.csp import (  # pyright: ignore[reportMissingImports], # ty: ignore[unresolved-import]
    CSP,
)
from loguru import logger

from codex.settings.config import (
    get_bool,
    get_float,
    get_int,
    get_str,
    load_codex_config,
)
from codex.settings.logging import get_logging_settings
from codex.settings.secret_key import get_secret_key
from codex.settings.servestatic import immutable_file_test
from codex.settings.timezone import get_time_zone

###########################
# Constants & Env Helpers #
###########################

FALSY = frozenset({None, "", "false", "0", False, "False"})


def not_falsy_env(name):
    """Return a boolean environment envs mindful of falsy values."""
    return environ.get(name, "").lower() not in FALSY


##############
# Base Paths #
##############

BASE_DIR = Path(__file__).resolve().parent.parent.parent
CODEX_PATH = BASE_DIR / "codex"
CONFIG_PATH = (
    Path(environ["CODEX_CONFIG_DIR"])
    if "CODEX_CONFIG_DIR" in environ
    else Path.cwd() / "config"
)

#####################
# Basic Environment #
#####################

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not_falsy_env("DEBUG")
BUILD = not_falsy_env("BUILD")
VITE_HOST = environ.get("VITE_HOST")
TZ = environ.get("TIMEZONE", environ.get("TZ"))
DOCKER_IMAGE_DEPRECATED = environ.get("DOCKER_IMAGE_DEPRECATED", "")

##########################
# Codex TOML Config Load #
##########################

CODEX_CONFIG_TOML = CONFIG_PATH / "codex.toml"
CODEX_CONFIG_TOML_DEFAULT = CODEX_PATH / "settings/codex.toml.default"
CODEX_CONFIG = load_codex_config(CODEX_CONFIG_TOML, CODEX_CONFIG_TOML_DEFAULT)

###################################
# Codex Config: Server (Granian)  #
###################################

GRANIAN_HOST = get_str(CODEX_CONFIG, "server.host", default="0.0.0.0")  # noqa: S104
GRANIAN_PORT = get_int(CODEX_CONFIG, "server.port", default=9810)
GRANIAN_WORKERS = get_int(CODEX_CONFIG, "server.workers", default=1)
GRANIAN_HTTP = get_str(CODEX_CONFIG, "server.http", default="auto")
GRANIAN_WEBSOCKETS = get_bool(CODEX_CONFIG, "server.websockets", default=True)
GRANIAN_URL_PATH_PREFIX = get_str(CODEX_CONFIG, "server.url_path_prefix", default="")
WATCH_FOR_CHANGES = DEBUG and get_bool(
    CODEX_CONFIG, "server.watch_for_changes", default=False
)

##############################
# Codex Config: Logging      #
##############################

LOGLEVEL = get_str(
    CODEX_CONFIG, "logging.loglevel", default="TRACE" if DEBUG else "INFO"
)
LOG_RETENTION = get_str(CODEX_CONFIG, "logging.log_retention", default="6 months")
LOG_DIR = Path(environ.get("CODEX_LOG_DIR", CONFIG_PATH / "logs"))
LOG_TO_CONSOLE = get_bool(CODEX_CONFIG, "logging.log_to_console", default=True)
LOG_TO_FILE = get_bool(CODEX_CONFIG, "logging.log_to_file", default=True)
LOG_PATH = LOG_DIR / "codex.log"
LOG_ROTATION = "10 MB"

##############################
# Codex Config: Auth         #
##############################

AUTH_REMOTE_USER = get_bool(CODEX_CONFIG, "auth.remote_user", default=False)

##############################
# Codex Config: Browser      #
##############################

BROWSER_MAX_OBJ_PER_PAGE = get_int(
    CODEX_CONFIG, "browser.max_obj_per_page", default=100
)

##############################
# Codex Config: Throttle     #
##############################

THROTTLE_ANON = get_int(CODEX_CONFIG, "throttle.anon", default=0)
THROTTLE_USER = get_int(CODEX_CONFIG, "throttle.user", default=0)
THROTTLE_OPDS = get_int(CODEX_CONFIG, "throttle.opds", default=0)
THROTTLE_OPENSEARCH = get_int(CODEX_CONFIG, "throttle.opensearch", default=0)

##############################
# Codex Config: Importer     #
##############################

# iterator(chunk_size=...) with prefetch_related at delete/comics.py:48
# Limit: memory only
# Previous: was working with 1000
IMPORTER_DELETE_MAX_CHUNK_SIZE = get_int(
    CODEX_CONFIG, "importer.delete_max_chunk_size", default=2000
)
# OR-chain Q()s in filters.py:32-43 and link/delete.py:37-41
# Limit: 990, 900 for safety.
IMPORTER_FILTER_BATCH_SIZE = get_int(
    CODEX_CONFIG, "importer.filter_batch_size", default=900
)
# This was derived with experiments long ago
IMPORTER_SEARCH_SYNC_BATCH_MEMORY_RATIO = get_float(
    CODEX_CONFIG, "importer.search_sync_batch_memory_ratio", default=3.2
)
# Batch size for slicing Comic paths into `filter(path__in=...)` queries.
# SQLite caps at 32766 variables; 30000 leaves headroom for the `library` param.
# path__in=batch_paths at links_fk.py:86
# Limit: 32760, 30000 is safe
IMPORTER_LINK_FK_BATCH_SIZE = get_int(
    CODEX_CONFIG, "importer.link_fk_batch_size", default=30000
)
# iterator(chunk_size=...) over prefetch-heavy qs at links_m2m.py:89
# Limit: memory + prefetch IN subqueries
IMPORTER_LINK_M2M_BATCH_SIZE = get_int(
    CODEX_CONFIG, "importer.link_m2m_batch_size", default=20000
)
# Comic bulk_update uses CASE WHEN pk=? THEN ? per field (2 params/field/row)
# plus 1 pk/row in WHERE IN. SQLite caps at 32766 variables; Django's
# auto-batching undercounts. 400 * (2*36 + 1) = 29200 leaves headroom.
# Limit: 448, 400 is safe.
IMPORTER_UPDATE_COMIC_BATCH_SIZE = get_int(
    CODEX_CONFIG, "importer.update_comic_batch_size", default=400
)
# SQLite page cache size (KiB) for the importer connection during a
# bulk import. The steady-state ``cache_size=-64000`` (64 MiB) is
# tuned for concurrent readers + slow-drip writes; a bulk import
# benefits from a much larger page cache so the working set fits.
# 512 MiB default; bump higher on big-RAM hosts, drop on Pi-class
# hosts with < 2 GiB RAM. Negative values are interpreted as KiB by
# SQLite per its PRAGMA documentation.
IMPORTER_SQLITE_CACHE_KB = get_int(
    CODEX_CONFIG, "importer.sqlite_cache_kb", default=524288
)
# Fraction of the process memory budget the chunked per-comic
# pipeline may use for in-flight comic state (Comic instances +
# LINK_FKS / LINK_M2MS / FTS payloads). The default keeps roughly
# three quarters of the budget free for SQLite cache + reference
# data + process overhead. Drop on memory-constrained hosts (small
# Pi, tight container limits) for finer-grained chunking; raise on
# big-RAM hosts to amortize per-chunk overhead. Clamped to
# [chunk floor, chunk ceiling] in the importer.
IMPORTER_CHUNK_MEM_FRACTION = get_float(
    CODEX_CONFIG, "importer.chunk_mem_fraction", default=0.25
)

##############################
# Codex Config: Librarian    #
##############################

# Worker count for the cover-creation ProcessPoolExecutor. The image
# pipeline (comicbox file read + PIL LANCZOS resize + WEBP encode) is
# CPU-bound and trivially parallel across cover targets. Default to
# the smaller of the box's CPU count and 8 - the cap bounds peak RAM
# (each worker holds PIL + comicbox + the open image, ~50-100 MB
# under load). Memory-tight installs (e.g. NAS with 1-2 GB total)
# should set this to 2.
COVER_WORKERS = get_int(
    CODEX_CONFIG,
    "librarian.cover_workers",
    default=min(cpu_count() or 1, 8),
)

##############################
# Codex Config: Debug        #
##############################

DEBUG_LOG_AUTH_HEADERS = get_bool(CODEX_CONFIG, "debug.log_auth_headers", default=False)
DEBUG_LOG_REQUEST = get_bool(CODEX_CONFIG, "debug.log_request", default=False)
DEBUG_LOG_RESPONSE_TIME = get_bool(
    CODEX_CONFIG, "debug.log_response_time", default=False
)
DEBUG_SLOW_QUERY_LIMIT = get_float(CODEX_CONFIG, "debug.slow_query_limit", default=0.5)

##############################
# Codex Env: Repair Flags    #
##############################

RESET_ADMIN = not_falsy_env("CODEX_RESET_ADMIN")
FIX_FOREIGN_KEYS = not_falsy_env("CODEX_FIX_FOREIGN_KEYS")
INTEGRITY_CHECK = not_falsy_env("CODEX_INTEGRITY_CHECK")
FTS_INTEGRITY_CHECK = not_falsy_env("CODEX_FTS_INTEGRITY_CHECK")
FTS_REBUILD = not_falsy_env("CODEX_FTS_REBUILD")

###############################################
#                                             #
#            Django Settings                  #
#                                             #
###############################################

############
# Security #
############

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret_key(CONFIG_PATH)
ALLOWED_HOSTS = ["*"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS: bool  # DEV EXPERIMENT
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [
        CSP.SELF,
        CSP.NONCE,
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-bundle.js",
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-standalone-preset.js",
    ],
    "style-src": [
        CSP.SELF,
        # Titanic amount of work to make this safe with vite
        CSP.UNSAFE_INLINE,
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css",
    ],
    "img-src": [
        "data:",
        CSP.SELF,
        "https://unpkg.com/pdfjs-dist/web/images/",
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/favicon-32x32.png",
    ],
    "connect-src": [
        CSP.SELF,
        "ws:",
        "wss:",
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css.map",
    ],
    # These are required by the vue-pdf-embed dependency pdfs-dist.
    # blob: being open is a little insecure and could possibly be narrowed with additional work.
    "worker-src": [CSP.SELF, CSP.NONCE, "blob:"],
    "script-src-elem": [CSP.SELF, CSP.NONCE, "data:"],
}

# Session
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 60  # 60 days

# Proxy headers
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Debug
INTERNAL_IPS = ("127.0.0.1",)

###########
# Logging #
###########
LOGGING = get_logging_settings(LOGLEVEL, debug=DEBUG)

######################
# Installed Apps     #
######################


def _get_installed_apps() -> tuple:
    installed_apps = [
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
    ]

    if DEBUG:
        # comes before static apps
        installed_apps += ["nplusone.ext.django", "schema_graph", "silk"]

    installed_apps += [
        "servestatic.runserver_nostatic",
        "django.contrib.staticfiles",
        "rest_framework",
        "rest_framework.authtoken",
        "rest_registration",
        "corsheaders",
    ]
    if not BUILD:
        installed_apps += [
            "django_vite",
        ]
    installed_apps += [
        "codex",
        "cachalot",
        "drf_spectacular",
    ]
    return tuple(installed_apps)


INSTALLED_APPS = _get_installed_apps()

##############
# Middleware #
##############


def _get_middleware() -> tuple:
    middleware = [
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "servestatic.middleware.ServeStaticMiddleware",
    ]
    if DEBUG:
        # Sits below ServeStaticMiddleware so silk only wraps the API
        # stack, not static file responses.
        middleware += ["silk.middleware.SilkyMiddleware"]
    middleware += [
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.middleware.csp.ContentSecurityPolicyMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
    ]
    if AUTH_REMOTE_USER:
        middleware += ["codex.authentication.HttpRemoteUserMiddleware"]
    middleware += [
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "codex.middleware.CodexMiddleware",
    ]
    if DEBUG:
        middleware += [
            "nplusone.ext.django.NPlusOneMiddleware",
        ]

    if DEBUG_LOG_RESPONSE_TIME:
        middleware += [
            "codex.middleware.LogResponseTimeMiddleware",
        ]
    if DEBUG_LOG_REQUEST:
        middleware += [
            "codex.middleware.LogRequestMiddleware",
        ]
    return tuple(middleware)


MIDDLEWARE = _get_middleware()

if DEBUG:
    NPLUSONE_LOGGER = logger
    NPLUSONE_LOG_LEVEL = "WARNING"

########################
# URL & WSGI Routing   #
########################

ROOT_URLCONF = "codex.urls.root"
WSGI_APPLICATION = "codex.wsgi.application"

#############
# Templates #
#############

CODEX_TEMPLATES = CODEX_PATH / "templates"
_DEV_LOADERS = MappingProxyType(
    {
        "loaders": [
            # Explicitly use non-cached loaders in dev to prevent handle retention
            ("django.template.loaders.filesystem.Loader",),
            ("django.template.loaders.app_directories.Loader",),
        ]
    }
)
_TEMPLATES_LOADERS = _DEV_LOADERS if DEBUG else {}
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [CODEX_TEMPLATES],
        "APP_DIRS": not DEBUG,
        "OPTIONS": {
            **_TEMPLATES_LOADERS,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.csp",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

############
# Database #
############

DB_PATH = CONFIG_PATH / "codex.sqlite3"

# Migrate old DB location
OLD_DB_PATH = CONFIG_PATH / "db.sqlite3"
if not DB_PATH.exists() and OLD_DB_PATH.exists():
    OLD_DB_PATH.rename(DB_PATH)

BACKUP_DB_DIR = CONFIG_PATH / "backups"
BACKUP_DB_PATH = (BACKUP_DB_DIR / DB_PATH.stem).with_suffix(DB_PATH.suffix + ".bak")

# Per-connection PRAGMAs. ``init_command`` fires on every new connection
# (which, with ``CONN_MAX_AGE=600``, means at most once per 10-minute
# window per worker). The pragma list below trades durability-of-a-
# single-unfsynced-write for throughput while staying safe under WAL:
#
# * ``journal_mode=wal`` — already in place; enables concurrent readers
#   alongside one writer, and lets ``synchronous=NORMAL`` be safe.
# * ``synchronous=NORMAL`` — fsync on checkpoint only, not per commit.
#   Under WAL the only risk is losing the last in-flight transaction on
#   a hard power-cut; the DB itself stays intact. Writes are ~2-5x faster.
# * ``temp_store=MEMORY`` — keep ORDER BY / GROUP BY / subquery scratch
#   in RAM rather than on-disk temp files. Matters for the browser's
#   heavy aggregate pages.
# * ``mmap_size=268435456`` (256 MiB) — memory-map the DB file so read
#   pages are served out of the page cache without ``read(2)``
#   syscalls. Cheap on 64-bit hosts, no-op on systems that reject the
#   mmap.
# * ``cache_size=-64000`` (negative ⇒ KiB, so 64 MiB) — larger in-memory
#   page cache. Most working sets in a typical codex library fit here,
#   turning repeat queries into pure RAM hits.
_SQLITE_PRAGMAS = (
    "PRAGMA journal_mode=wal;"
    "PRAGMA synchronous=NORMAL;"
    "PRAGMA temp_store=MEMORY;"
    "PRAGMA mmap_size=268435456;"
    "PRAGMA cache_size=-64000;"
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_PATH,
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "init_command": _SQLITE_PRAGMAS,
            "timeout": 120,
        },
    },
}

if DEBUG:
    # django-silk captures live in their own DB so perf traces don't
    # bloat the app DB and can be wiped with a single rm.
    SILK_DB_PATH = CONFIG_PATH / "silk.sqlite3"
    DATABASES["silky"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": SILK_DB_PATH,
        "OPTIONS": {"init_command": _SQLITE_PRAGMAS, "timeout": 120},
    }
    DATABASE_ROUTERS = ["codex.db_routers.SilkRouter"]

# Django 6 defaults DEFAULT_AUTO_FIELD to ``BigAutoField`` (64-bit).
# Pin it here to match — explicit ``> AutoField`` migration support
# landed in Django 4.0 (ticket #32674) so the legacy 32-bit override
# this codebase carried since Django 3.2 is no longer needed.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

##################
# Authentication #
##################

if AUTH_REMOTE_USER:
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.RemoteUserBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        )
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 4},
    },
]

########################
# Internationalization #
########################

LANGUAGE_CODE = "en-us"
USE_I18N = True
TIME_ZONE = get_time_zone(TZ)

################
# Static Files #
################

STATIC_ROOT = CODEX_PATH / "static"
SERVESTATIC_IMMUTABLE_FILE_TEST = immutable_file_test
SERVESTATIC_USE_ZSTD = False  # only a win for dynamic files
SERVESTATIC_STATIC_PREFIX = "/static"  # otherwise is based on STATIC_URL
STATIC_URL = GRANIAN_URL_PATH_PREFIX.rstrip("/") + SERVESTATIC_STATIC_PREFIX + "/"
STORAGES = {
    "staticfiles": {
        # Don't use Manifest storage because vite does that for me and saves space.
        "BACKEND": "servestatic.storage.CompressedStaticFilesStorage",
    }
}
STATICFILES_DIRS = (
    [CODEX_PATH / "static_src", CODEX_PATH / "static_build"] if (DEBUG or BUILD) else []
)
for path in STATICFILES_DIRS:
    path.mkdir(exist_ok=True, parents=True)

#########
# Cache #
#########

ROOT_CACHE_PATH = CONFIG_PATH / "cache"
DEFAULT_CACHE_PATH = ROOT_CACHE_PATH / "default"
DEFAULT_CACHE_PATH.mkdir(exist_ok=True, parents=True)
# MAX_ENTRIES defaults to 300 in Django's FileBasedCache. That's far
# too small once the cache holds (a) cachalot query results — often
# 100+ unique SELECTs per browse page — plus (b) `cache_page` entries
# for the browser view AND (c) one `cache_page` entry per cover pk on
# the cover endpoint. A 100-cover page can populate 200+ entries in a
# single pageload; the default triggers the 2/3 random cull, which
# silently evicts just-written cover responses before the next request
# can read them. 10k is cheap on disk (~<100 MB of tiny files) and
# cheap at cull time (FileBasedCache walks the dir — negligible at 10k).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": str(DEFAULT_CACHE_PATH),
        "OPTIONS": {"MAX_ENTRIES": 10000},
    },
}

##################
# REST Framework #
##################

_THROTTLE_MAP = MappingProxyType(
    {
        "anon": ("rest_framework.throttling.AnonRateThrottle", THROTTLE_ANON),
        "user": ("rest_framework.throttling.UserRateThrottle", THROTTLE_USER),
        "opds": ("rest_framework.throttling.ScopedRateThrottle", THROTTLE_OPDS),
        "opensearch": (
            "rest_framework.throttling.ScopedRateThrottle",
            THROTTLE_OPENSEARCH,
        ),
    }
)
_THROTTLE_CLASSES = set()
_THROTTLE_RATES = {}
for scope, (classname, rate_value) in _THROTTLE_MAP.items():
    if rate_value or classname == "rest_framework.throttling.ScopedRateThrottle":
        _THROTTLE_CLASSES.add(classname)
        _THROTTLE_RATES[scope] = f"{rate_value}/min" if rate_value else None

_RENDERER_CLASSES = [
    "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
]
if DEBUG:
    _RENDERER_CLASSES.append(
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer"
    )
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "codex.authentication.BearerTokenAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": tuple(_RENDERER_CLASSES),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "codex.views.error.codex_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": tuple(_THROTTLE_CLASSES),
    "DEFAULT_THROTTLE_RATES": _THROTTLE_RATES,
}

#####################
# REST Registration #
#####################

REST_REGISTRATION = {
    "REGISTER_VERIFICATION_ENABLED": False,
    "REGISTER_EMAIL_VERIFICATION_ENABLED": False,
    "RESET_PASSWORD_VERIFICATION_ENABLED": False,
    "USER_HIDDEN_FIELDS": (
        # DEFAULT
        "last_login",
        "is_active",
        "user_permissions",
        "groups",
        "date_joined",
        # SHOWN
        # "is_staff", "is_superuser",
        # HIDDEN
        "email",
        "first_name",
        "last_name",
    ),
}

#####################
# API Documentation #
#####################

SPECTACULAR_SETTINGS = {
    "TITLE": "Codex API",
    "DESCRIPTION": "Comic Library Browser and Reader",
    "OAS_VERSION": "3.1.0",
    "VERSION": "3.0.0",
    "CONTACT": {
        "name": "Support",
        "url": "https://github.com/ajslater/codex?tab=readme-ov-file#-support",
    },
    "PREPROCESSING_HOOKS": ["codex.urls.spectacular.allow_list"],
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"],
    "EXTERNAL_DOCS": {
        "url": "https://codex-comic-reader.readthedocs.io/",
        "description": "Codex Docs",
    },
    "ENUM_NAME_OVERRIDES": {
        # group
        "BrowseGroupEnum": "codex.serializers.fields.group.BrowseGroupField.class_choices",
        "BrowserRouteGroupEnum": "codex.serializers.fields.group.BrowserRouteGroupField.class_choices",
        # reading_direction
        "BookmarkReadingDirectionEnum": "codex.models.choices.ReadingDirectionChoices.choices",
        "ReaderReadingDirectionEnum": "codex.serializers.fields.reader.ReadingDirectionField.class_choices",
        "VuetifyReadingDirectionEnum": "codex.serializers.fields.vuetify.VuetifyReadingDirectionChoiceField.class_choices",
    },
}


############
# Channels #
############

CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
}

###############
# Django Vite #
###############

if DEBUG and not BUILD:
    import socket

    DEV_SERVER_HOST = VITE_HOST or socket.gethostname()
    DJANGO_VITE = {
        "default": {
            "dev_mode": DEBUG,
            "dev_server_host": DEV_SERVER_HOST,
        }
    }
    CSP_SCRIPT_SRC = ("'self'", "http://localhost:5173", "'nonce'")
    CSP_CONNECT_SRC = ("'self'", "ws://localhost:5173", "http://localhost:5173")

############
# Cachalot #
############

CACHALOT_UNCACHABLE_TABLES = frozenset({"django_migrations", "django_session"})

########
# Silk #
########

if DEBUG:
    # SQL-level capture only. CPU profiling is off by default; flip on
    # when profiling cover generation or other CPU-bound paths.
    SILKY_PYTHON_PROFILER = False
    # Record silk's own overhead so we can subtract it from wall-time.
    SILKY_META = True
    # Do not cap body sizes — perf flows are small JSON payloads.
    SILKY_MAX_REQUEST_BODY_SIZE = 0
    SILKY_MAX_RESPONSE_BODY_SIZE = 0
    # Require login to view the silk UI; only superusers can see it.
    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True
    SILKY_PERMISSIONS = lambda user: user.is_superuser  # noqa: E731


#################
# Custom Covers #
#################

CUSTOM_COVERS_SUBDIR = "custom-covers"
CUSTOM_COVERS_DIR = CONFIG_PATH / CUSTOM_COVERS_SUBDIR
CUSTOM_COVERS_GROUP_DIRS = frozenset(
    {"publishers", "imprints", "series", "volumes", "story-arcs"}
)


def create_custom_cover_group_dirs() -> None:
    """Create custom cover group dirs."""
    for group_dir in CUSTOM_COVERS_GROUP_DIRS:
        custom_cover_group_dir = CUSTOM_COVERS_DIR / group_dir
        custom_cover_group_dir.mkdir(exist_ok=True, parents=True)


create_custom_cover_group_dirs()

############
# Comicbox #
############

# Top-level comicbox fields the importer actually consumes. Source of
# truth for the codex<->comicbox contract — the importer's
# ``aggregate_path`` code drops anything outside this set, and the
# ``delete_keys`` config below tells comicbox to skip parse work for
# everything else.
#
# Three entries (``file_type``, ``metadata_mtime``, ``path``) are
# codex-side extras populated by ``comicbox/process.py``'s ``_read_one``
# rather than from the parsed metadata; they are intentionally not in
# the ``ComicboxYamlSubSchema`` field set.
USED_COMICBOX_FIELDS: frozenset[str] = frozenset(
    {
        "age_rating",
        "arcs",
        "characters",
        "collection_title",
        "country",
        "credits",
        "critical_rating",
        "date",
        "file_type",  # codex-side extra
        "genres",
        "identifiers",
        "imprint",
        "issue",
        "language",
        "locations",
        "metadata_mtime",  # codex-side extra
        "monochrome",
        "notes",
        "original_format",
        "path",  # codex-side extra
        "page_count",
        "protagonist",
        "publisher",
        "reading_direction",
        "review",
        "scan_info",
        "series",
        "series_groups",
        "stories",
        "summary",
        "tagger",
        "tags",
        "teams",
        "title",
        "universes",
        "volume",
    }
)

# Tell comicbox to skip parse work for every top-level field codex
# does not consume. Pages and reprints are short-circuited inside
# their respective computed actions; the rest are excluded at schema
# parse time and dropped post-merge as a backstop. Derived from the
# live comicbox schema rather than hand-curated so a comicbox release
# that adds a new top-level field is auto-deleted (codex maintainer
# adds it to ``USED_COMICBOX_FIELDS`` if it's needed). Closes the
# pre-existing ``cover_image`` gap.
#
# ``_declared_fields`` is the standard marshmallow class-level field
# registry; it has been the public-by-convention enumeration surface
# for marshmallow schemas since 3.x.
_COMICBOX_DELETE_KEYS: frozenset[str] = frozenset(
    ComicboxYamlSubSchema._declared_fields.keys()  # noqa: SLF001
    - USED_COMICBOX_FIELDS
)

COMICBOX_CONFIG = FrozenAttrDict(
    get_config(
        {
            "loglevel": LOGLEVEL,
            "delete_keys": _COMICBOX_DELETE_KEYS,
        }
    )
)
