"""
Django settings for codex project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from os import environ
from pathlib import Path
from types import MappingProxyType

from comicbox.config import get_config
from django.utils.csp import CSP
from loguru import logger

from codex.settings.config import (
    get_bool,
    get_float,
    get_int,
    get_str,
    load_codex_config,
)
from codex.settings.secret_key import get_secret_key
from codex.settings.timezone import get_time_zone
from codex.settings.whitenoise import immutable_file_test

###########################
# Constants & Env Helpers #
###########################

FALSY = frozenset({None, "", "false", "0", False, "False"})


def not_falsy_env(name):
    """Return a boolean environment envs mindful of falsy values."""
    return bool(environ.get(name, "").lower() not in FALSY)


##############
# Base Paths #
##############

BASE_DIR = Path(__file__).resolve().parent.parent.parent
CODEX_PATH = BASE_DIR / "codex"
CONFIG_PATH = Path(environ.get("CODEX_CONFIG_DIR", Path.cwd() / "config"))

#####################
# Basic Environment #
#####################

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not_falsy_env("DEBUG")
BUILD = not_falsy_env("BUILD")
VITE_HOST = environ.get("VITE_HOST")
TZ = environ.get("TIMEZONE", environ.get("TZ"))

##########################
# Codex TOML Config Load #
##########################

CODEX_CONFIG_TOML = CONFIG_PATH / "codex.toml"
CODEX_CONFIG_TOML_DEFAULT = CODEX_PATH / "settings/codex.toml.default"
CODEX_CONFIG = load_codex_config(CODEX_CONFIG_TOML, CODEX_CONFIG_TOML_DEFAULT)

###################################
# Codex Config: Server (Granian)  #
###################################

GRANIAN_HOST = get_str(CODEX_CONFIG, "server.host", default="0.0.0.0")  # noqa: S104
GRANIAN_PORT = get_int(CODEX_CONFIG, "server.port", default=9810)
GRANIAN_WORKERS = get_int(CODEX_CONFIG, "server.workers", default=1)
GRANIAN_HTTP = get_str(CODEX_CONFIG, "server.http", default="auto")
GRANIAN_WEBSOCKETS = get_bool(CODEX_CONFIG, "server.websockets", default=True)
GRANIAN_URL_PATH_PREFIX = get_str(CODEX_CONFIG, "server.url_path_prefix", default="")

##############################
# Codex Config: Logging      #
##############################

LOGLEVEL = get_str(
    CODEX_CONFIG, "logging.loglevel", default="TRACE" if DEBUG else "INFO"
)
LOG_RETENTION = get_str(CODEX_CONFIG, "logging.log_retention", default="6 months")
LOG_DIR = Path(environ.get("CODEX_LOG_DIR", CONFIG_PATH / "logs"))
LOG_TO_CONSOLE = get_bool(CODEX_CONFIG, "logging.log_to_console", default=True)
LOG_TO_FILE = get_bool(CODEX_CONFIG, "logging.log_to_file", default=True)
LOG_PATH = LOG_DIR / "codex.log"
LOG_ROTATION = "10 MB"

##############################
# Codex Config: Auth         #
##############################

AUTH_REMOTE_USER = get_bool(CODEX_CONFIG, "auth.remote_user", default=False)

##############################
# Codex Config: Browser      #
##############################

BROWSER_MAX_OBJ_PER_PAGE = get_int(
    CODEX_CONFIG, "browser.max_obj_per_page", default=100
)

##############################
# Codex Config: Throttle     #
##############################

THROTTLE_ANON = get_int(CODEX_CONFIG, "throttle.anon", default=0)
THROTTLE_USER = get_int(CODEX_CONFIG, "throttle.user", default=0)
THROTTLE_OPDS = get_int(CODEX_CONFIG, "throttle.opds", default=0)
THROTTLE_OPENSEARCH = get_int(CODEX_CONFIG, "throttle.opensearch", default=0)

##############################
# Codex Config: Importer     #
##############################

IMPORTER_DELETE_MAX_CHUNK_SIZE = get_int(
    CODEX_CONFIG, "importer.delete_max_chunk_size", default=1000
)
IMPORTER_FILTER_BATCH_SIZE = get_int(
    CODEX_CONFIG, "importer.filter_batch_size", default=900
)
IMPORTER_SEARCH_SYNC_BATCH_MEMORY_RATIO = get_float(
    CODEX_CONFIG, "importer.search_sync_batch_memory_ratio", default=3.2
)
IMPORTER_LINK_FK_BATCH_SIZE = get_int(
    CODEX_CONFIG, "importer.link_fk_batch_size", default=20000
)
IMPORTER_LINK_M2M_BATCH_SIZE = get_int(
    CODEX_CONFIG, "importer.link_m2m_batch_size", default=20000
)

##############################
# Codex Config: Debug        #
##############################

DEBUG_LOG_AUTH_HEADERS = get_bool(CODEX_CONFIG, "debug.log_auth_headers", default=False)
DEBUG_LOG_REQUEST = get_bool(CODEX_CONFIG, "debug.log_request", default=False)
DEBUG_LOG_RESPONSE_TIME = get_bool(
    CODEX_CONFIG, "debug.log_response_time", default=False
)
DEBUG_SLOW_QUERY_LIMIT = get_float(CODEX_CONFIG, "debug.slow_query_limit", default=0.5)

##############################
# Codex Env: Repair Flags    #
##############################

RESET_ADMIN = not_falsy_env("CODEX_RESET_ADMIN")
FIX_FOREIGN_KEYS = not_falsy_env("CODEX_FIX_FOREIGN_KEYS")
INTEGRITY_CHECK = not_falsy_env("CODEX_INTEGRITY_CHECK")
FTS_INTEGRITY_CHECK = not_falsy_env("CODEX_FTS_INTEGRITY_CHECK")
FTS_REBUILD = not_falsy_env("CODEX_FTS_REBUILD")

###############################################
#                                             #
#            Django Settings                  #
#                                             #
###############################################

############
# Security #
############

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret_key(CONFIG_PATH)
ALLOWED_HOSTS = ["*"]
CORS_ALLOW_CREDENTIALS = True
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [
        CSP.SELF,
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-bundle.js",
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-standalone-preset.js",
    ],
    "style-src": [
        CSP.SELF,
        # Titanic amount of work to make this safe with vite
        CSP.UNSAFE_INLINE,
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css",
    ],
    "img-src": [
        "data:",
        CSP.SELF,
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/favicon-32x32.png",
    ],
    "connect-src": [
        CSP.SELF,
        "ws:",
        "wss:",
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css.map",
    ],
}

# Session
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 60  # 60 days

# Proxy headers
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

###########
# Logging #
###########


def _get_logging() -> dict[str, int | dict]:
    loggers = {}
    if LOGLEVEL != "TRACE":
        loggers.update(
            {
                "asyncio": {
                    "level": "INFO",
                },
            }
        )
    if not DEBUG:
        loggers.update(
            {
                "urllib3.connectionpool": {"level": "INFO"},
                "PIL": {
                    "level": "INFO",
                },
            }
        )
    return {"version": 1, "loggers": loggers}


LOGGING = _get_logging()

######################
# Installed Apps     #
######################


def _get_installed_apps() -> tuple:
    installed_apps = [
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
    ]

    if DEBUG:
        # comes before static apps
        installed_apps += ["nplusone.ext.django", "schema_graph"]

    installed_apps += [
        "whitenoise.runserver_nostatic",
        "django.contrib.staticfiles",
        "rest_framework",
        "rest_framework.authtoken",
        "rest_registration",
        "corsheaders",
    ]
    if not BUILD:
        installed_apps += [
            "django_vite",
        ]
    installed_apps += [
        "codex",
        "cachalot",
        "drf_spectacular",
    ]
    return tuple(installed_apps)


INSTALLED_APPS = _get_installed_apps()

##############
# Middleware #
##############


def _get_middleware() -> tuple:
    middleware = [
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.middleware.csp.ContentSecurityPolicyMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
    ]
    if AUTH_REMOTE_USER:
        middleware += ["codex.authentication.HttpRemoteUserMiddleware"]
    middleware += [
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "codex.middleware.TimezoneMiddleware",
    ]
    if DEBUG:
        middleware += [
            "nplusone.ext.django.NPlusOneMiddleware",
        ]

    if DEBUG_LOG_RESPONSE_TIME:
        middleware += [
            "codex.middleware.LogResponseTimeMiddleware",
        ]
    if DEBUG_LOG_REQUEST:
        middleware += [
            "codex.middleware.LogRequestMiddleware",
        ]
    return tuple(middleware)


MIDDLEWARE = _get_middleware()

if DEBUG:
    NPLUSONE_LOGGER = logger
    NPLUSONE_LOG_LEVEL = "WARNING"

########################
# URL & WSGI Routing   #
########################

ROOT_URLCONF = "codex.urls.root"
WSGI_APPLICATION = "codex.wsgi.application"

#############
# Templates #
#############

CODEX_TEMPLATES = CODEX_PATH / "templates"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [CODEX_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.csp",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

############
# Database #
############

DB_PATH = CONFIG_PATH / "codex.sqlite3"

# Migrate old DB location
OLD_DB_PATH = CONFIG_PATH / "db.sqlite3"
if not DB_PATH.exists() and OLD_DB_PATH.exists():
    OLD_DB_PATH.rename(DB_PATH)

BACKUP_DB_DIR = CONFIG_PATH / "backups"
BACKUP_DB_PATH = (BACKUP_DB_DIR / DB_PATH.stem).with_suffix(DB_PATH.suffix + ".bak")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_PATH,
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "init_command": "PRAGMA journal_mode=wal;",
            "timeout": 120,
        },
    },
}

# The new DEFAULT_AUTO_FIELD in Django 3.2 is BigAutoField (64 bit),
#   but it can't be auto migrated. Automigration has been punted to
#   Django 4.0 at the earliest:
#   https://code.djangoproject.com/ticket/32674
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

##################
# Authentication #
##################

if AUTH_REMOTE_USER:
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.RemoteUserBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        )
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 4},
    },
]

########################
# Internationalization #
########################

LANGUAGE_CODE = "en-us"
USE_I18N = True
TIME_ZONE = get_time_zone(TZ)

################
# Static Files #
################

# WHITENOISE_KEEP_ONLY_HASHED_FILES is still not usable with vite chunking
# If it is, than maybe don't need this immutable_file_test
STATIC_ROOT = CODEX_PATH / "static"
WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test
WHITENOISE_STATIC_PREFIX = "/static"  # otherwise is based on STATIC_URL
STATIC_URL = GRANIAN_URL_PATH_PREFIX.rstrip("/") + WHITENOISE_STATIC_PREFIX + "/"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
}
STATICFILES_DIRS = (
    [CODEX_PATH / "static_src", CODEX_PATH / "static_build"] if (DEBUG or BUILD) else []
)
for path in STATICFILES_DIRS:
    path.mkdir(exist_ok=True, parents=True)

#########
# Cache #
#########

ROOT_CACHE_PATH = CONFIG_PATH / "cache"
DEFAULT_CACHE_PATH = ROOT_CACHE_PATH / "default"
DEFAULT_CACHE_PATH.mkdir(exist_ok=True, parents=True)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": str(DEFAULT_CACHE_PATH),
    },
}

##################
# REST Framework #
##################

_THROTTLE_MAP = MappingProxyType(
    {
        "anon": ("rest_framework.throttling.AnonRateThrottle", THROTTLE_ANON),
        "user": ("rest_framework.throttling.UserRateThrottle", THROTTLE_USER),
        "opds": ("rest_framework.throttling.ScopedRateThrottle", THROTTLE_OPDS),
        "opensearch": (
            "rest_framework.throttling.ScopedRateThrottle",
            THROTTLE_OPENSEARCH,
        ),
    }
)
_THROTTLE_CLASSES = set()
_THROTTLE_RATES = {}
for scope, value in _THROTTLE_MAP.items():
    classname, rate_value = value
    if rate_value or classname == "rest_framework.throttling.ScopedRateThrottle":
        _THROTTLE_CLASSES.add(classname)
        rate = f"{rate_value}/min" if value[1] else None
        _THROTTLE_RATES[scope] = rate

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "codex.authentication.BearerTokenAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        # "djangorestframework_camel_case.parser.CamelCaseFormParser",
        # "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "codex.views.error.codex_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": tuple(_THROTTLE_CLASSES),
    "DEFAULT_THROTTLE_RATES": _THROTTLE_RATES,
}

#####################
# REST Registration #
#####################

REST_REGISTRATION = {
    "REGISTER_VERIFICATION_ENABLED": False,
    "REGISTER_EMAIL_VERIFICATION_ENABLED": False,
    "RESET_PASSWORD_VERIFICATION_ENABLED": False,
    "USER_HIDDEN_FIELDS": (
        # DEFAULT
        "last_login",
        "is_active",
        "user_permissions",
        "groups",
        "date_joined",
        # SHOWN
        # "is_staff", "is_superuser",
        # HIDDEN
        "email",
        "first_name",
        "last_name",
    ),
}

#####################
# API Documentation #
#####################

SPECTACULAR_SETTINGS = {
    "TITLE": "Codex API",
    "DESCRIPTION": "Comic Library Browser and Reader",
    "OAS_VERSION": "3.1.0",
    "VERSION": "3.0.0",
    "CONTACT": {
        "name": "Support",
        "url": "https://github.com/ajslater/codex?tab=readme-ov-file#-support",
    },
    "PREPROCESSING_HOOKS": ["codex.urls.spectacular.allow_list"],
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"],
    "EXTERNAL_DOCS": {
        "url": "https://codex-comic-reader.readthedocs.io/",
        "description": "Codex Docs",
    },
    "ENUM_NAME_OVERRIDES": {
        # group
        "BrowseGroupEnum": "codex.serializers.fields.group.BrowseGroupField.class_choices",
        "BrowserRouteGroupEnum": "codex.serializers.fields.group.BrowserRouteGroupField.class_choices",
        # reading_direction
        "BookmarkReadingDirectionEnum": "codex.models.choices.ReadingDirectionChoices.choices",
        "ReaderReadingDirectionEnum": "codex.serializers.fields.reader.ReadingDirectionField.class_choices",
        "VuetifyReadingDirectionEnum": "codex.serializers.fields.vuetify.VuetifyReadingDirectionChoiceField.class_choices",
    },
}


############
# Channels #
############

CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
}

###############
# Django Vite #
###############

if DEBUG and not BUILD:
    import socket

    DEV_SERVER_HOST = VITE_HOST or socket.gethostname()
    DJANGO_VITE = {
        "default": {
            "dev_mode": DEBUG,
            "dev_server_host": DEV_SERVER_HOST,
        }
    }

############
# Cachalot #
############

CACHALOT_UNCACHABLE_TABLES = frozenset(
    {"django_migrations", "django_session", "codex_useractive"}
)

INTERNAL_IPS = ("127.0.0.1",)

#################
# Custom Covers #
#################

CUSTOM_COVERS_SUBDIR = "custom-covers"
CUSTOM_COVERS_DIR = CONFIG_PATH / CUSTOM_COVERS_SUBDIR
CUSTOM_COVERS_GROUP_DIRS = frozenset(
    {"publishers", "imprints", "series", "volumes", "story-arcs"}
)


def create_custom_cover_group_dirs() -> None:
    """Create custom cover group dirs."""
    for group_dir in CUSTOM_COVERS_GROUP_DIRS:
        custom_cover_group_dir = CUSTOM_COVERS_DIR / group_dir
        custom_cover_group_dir.mkdir(exist_ok=True, parents=True)


create_custom_cover_group_dirs()

############
# Comicbox #
############

COMICBOX_CONFIG = get_config(
    {
        "loglevel": LOGLEVEL,
        "delete_keys": frozenset(
            {
                # Only pages and reprints are optimized away for sure with comicbox 2.0.2
                "alternate_images",
                "bookmark",
                "credit_primaries",
                "ext",
                "identifier_primary_source",
                "manga",
                "pages",
                "prices",
                "remainders",
                "reprints",
                "rights",
                "updated_at",
            }
        ),
    }
)
