comicbox:
  comet: True
  comicbookinfo: True
  comicinfoxml: True
  delete_orig: False
  delete_tags: False
  dest_path: .
  dry_run: False
  filename: True
  raw: False
  recurse: False
  metadata: {}
  close_fd: True
  check_unrar: False
