comicbox:
  delete_orig: False
  delete_tags: False
  dest_path: .
  dry_run: False
  raw: False
  read_comet: True
  read_comicbookinfo: True
  read_comicinfoxml: True
  read_filename: True
  read_pdf: True
  recurse: False
  metadata: {}
  close_fd: True
  check_unrar: False
  write_comet: False
  write_comicbookinfo: False
  write_comicinfoxml: False
  write_filename: False
  write_pdf: False
